- startHbz01ToLobidResources.sh
> Add start script

- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT014215912
- src/test/resources/jsonld/HT014319164
- src/test/resources/jsonld/HT015440386
- src/test/resources/jsonld/HT015455455
- src/test/resources/jsonld/HT015891797
- src/test/resources/jsonld/HT017529028
- src/test/resources/jsonld/HT018239864
- src/test/resources/jsonld/HT018295975
- src/test/resources/jsonld/HT018312899
- src/test/resources/jsonld/HT018726005
The gnd ontology is used to predicate the values.
See lobid-lodmill#771.
- update tests
> Add birth/death dates as statements for persons

- src/main/java/org/lobid/resources/RdfModel2ElasticsearchEtikettJsonLd.java
The regex now disallows ZDB-URIs and URIS ending with "about" to be
internal_ids.
See #30.
> Fix getting internal_id by using improved regex

- src/main/java/org/lobid/resources/run/DownloadTestSet.java
- src/test/resources/buildAndETLTestSet.sh
> Set encoding an update script comment

- README.textile
- jsonDiffAndCopy.sh
> Add how to change transformations and update tests

- startHbz01ToLobidResources.sh
Sometimes the pulling is done in the crontab commands, sometimes
not. It is the best to always pull explicitly in the script.
> Add "git pull" to start script

- README.textile
- restructure the two possible outcomes
> Add commands to execute when adding a resource

- pom.xml
- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
> Adjust URIs for RDA elements

- pom.xml
- src/main/java/org/lobid/resources/RdfModel2ElasticsearchEtikettJsonLd.java
See https://github.com/hbz/lobid-rdf-to-json/pull/38.
> Use adjusted version of lobid-rdf-to-json. (#33).

- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT003160768
> Adjust morph and test files for use of rdau:P60327

- pom.xml
- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT012895751
- src/test/resources/jsonld/HT014319164
- src/test/resources/jsonld/HT014997977
- src/test/resources/jsonld/HT015455455
- src/test/resources/jsonld/HT015865114
- src/test/resources/jsonld/HT015891797
- src/test/resources/jsonld/HT016382441
- src/test/resources/jsonld/HT018239864
- src/test/resources/jsonld/HT018295975
- src/test/resources/jsonld/HT018468645
- src/test/resources/jsonld/HT018585406
- src/test/resources/jsonld/HT018895767
- src/test/resources/jsonld/TT001671747
> Add RPB Sachgruppen to lobid RDF

- src/main/resources/index-config.json
> 84 update type in index config

- src/test/resources/buildAndETLTestSet.sh
This issue is a consequence of #94.
> Update cluster name

- src/main/java/org/lobid/resources/run/GetRdaDocsInMabXml.java
- src/main/resources/morph-getHbz01Rda.xml
Will partly resolve hbz/lobid#161.
> Add morph and run class for filtering rda documents

- pom.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/BT000002852
- src/test/resources/jsonld/CT003012479
- src/test/resources/jsonld/HT014015351
- src/test/resources/jsonld/HT014319164
- src/test/resources/jsonld/HT014681992
- src/test/resources/jsonld/HT015891797
- src/test/resources/jsonld/HT016604323
- src/test/resources/jsonld/HT018295975
- src/test/resources/jsonld/HT018454638
- src/test/resources/jsonld/HT018612706
- src/test/resources/jsonld/HT018771475
- src/test/resources/jsonld/HT018924091
This fixes #107 (missing rdf:type for repeated objects).
> Update dependency of lobid-rdf-to-json

- pom.xml
- src/main/resources/index-config.json
- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT015894164
- src/test/resources/jsonld/HT018771475
Reverts hbz/lobid-resources#148
> Revert "50 is part of name"

- pom.xml
- src/main/resources/index-config.json
- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT015894164
- src/test/resources/jsonld/HT018771475
See #50.
This is the exactly same Pull Request as #148 but without the rejected commits of #147.
> Change "isPartOfName" to be a bnode named "isPartOf"

- README.textile
- fix some typos
See also #142.
> Update README: how to deploy context.json

- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT004944075
- src/test/resources/output/json/00494/HT004944075.json
- src/test/resources/reverseTest/output/nt/00494/HT004944075.nt
See hbz/lobid-resources-web#18.
> Normalize date of "issued"

- src/main/resources/index-config.json
> Changed index for exemplar.id to "not_analyzed"

- web/app/views/tags/result_doc.scala.html
- web/conf/resources.conf
Will resolve https://github.com/hbz/lobid-resources-web/issues/22, and resolve https://github.com/hbz/lobid-resources-web/issues/23.
Deployed to staging, see:
http://test.lobid.org/resources/HT002732102
http://test.lobid.org/resources/HT018314858
> Updates for details view

- web/app/views/api.scala.html
New example contains also altLabels, corporateBody and is set as a simple monograph. @fsteeg Please set the URL so I can annotate also on the test system.
See #189
> Add new example as replacement for Buch

- web/app/controllers/resources/Index.java
- web/app/views/tags/result_doc.scala.html
- web/test/tests/IndexUnitTest.java
Will resolve https://github.com/hbz/lobid-resources-web/issues/34
Deployed to staging, see:
http://test.lobid.org/resources/search?id=9783922608721 (ISBN search)
http://test.lobid.org/resources/search?id=16187792 (ISSN search)
http://test.lobid.org/resources/HT013304490 (ISSN in details)
> Support ISSN in advanced ID search, display ISSN in details

- src/main/resources/labels/labels.json
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT013077595
- src/test/resources/jsonld/TT001671747
- src/test/resources/output/json/00167/TT001671747.json
- src/test/resources/output/json/01307/HT013077595.json
- src/test/resources/reverseTest/output/nt/00167/TT001671747.nt
- src/test/resources/reverseTest/output/nt/01307/HT013077595.nt
> Change role label from Redaktor to Redaktion

- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT017411546
- src/test/resources/jsonld/HT018895767
- src/test/resources/jsonld/HT018907266
- src/test/resources/jsonld/HT018939763
- src/test/resources/jsonld/HT019011249
- src/test/resources/output/json/01889/HT018895767.json
- src/test/resources/output/json/01890/HT018907266.json
- src/test/resources/output/json/01893/HT018939763.json
- src/test/resources/output/json/01901/HT019011249.json
- src/test/resources/reverseTest/output/nt/01889/HT018895767.nt
- src/test/resources/reverseTest/output/nt/01890/HT018907266.nt
- src/test/resources/reverseTest/output/nt/01893/HT018939763.nt
- src/test/resources/reverseTest/output/nt/01901/HT019011249.nt
> Remove meium "Electronic Resource" from online resources.

- src/main/resources/morph-hbz01-to-lobid.xml
Also corrects regexp
Resolves #215
> Combine definitions of book type

- web/app/controllers/resources/Application.java
- web/app/controllers/resources/Index.java
- web/app/controllers/resources/Lobid.java
- web/app/views/tags/items_map.scala.html
- web/conf/resources.conf
- web/test/tests/ExternalIntegrationTest.java
Will resolve https://github.com/hbz/lobid-resources-web/issues/27
Deployed to staging, see:
http://test.lobid.org/resources/search?q=ehrenfeld (facet labels: subjects, owners)
http://test.lobid.org/items/HT017557310:DE-38:RHKAS7068#! (resource label above map)
> Get labels from 2.0 index

- web/app/controllers/resources/Accept.java
- web/app/controllers/resources/Application.java
- web/app/controllers/resources/Index.java
- web/app/views/tags/search_advanced.scala.html
- web/test/tests/AcceptUnitTest.java
Will resolve https://github.com/hbz/lobid-resources-web/issues/28
Also enable autosuggest for agent and subject search (in addition to title).
Deployed to staging: http://test.lobid.org/resources/advanced
> Switch advanced search autosuggest to internal API

- src/main/java/de/hbz/lobid/helper/CompareJsonMaps.java
- src/main/resources/context.json
- src/main/resources/labels/labels.json
- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/java/org/lobid/resources/Hbz01MabXml2ElasticsearchLobidTest.java
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT000009600
- src/test/resources/jsonld/HT013304490
- src/test/resources/jsonld/HT017411546
- src/test/resources/output/json/00000/HT000009600.json
- src/test/resources/output/json/01330/HT013304490.json
- src/test/resources/output/json/01741/HT017411546.json
- src/test/resources/reverseTest/output/nt/00000/HT000009600.nt
- src/test/resources/reverseTest/output/nt/01330/HT013304490.nt
- src/test/resources/reverseTest/output/nt/01741/HT017411546.nt
Also changed variable name from @hasSupplement to supplement.
See #230
> Replace RDA for bibframe/supplement

- src/main/java/de/hbz/lobid/helper/CompareJsonMaps.java
- src/main/resources/context.json
- src/main/resources/labels/labels.json
- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/java/org/lobid/resources/Hbz01MabXml2ElasticsearchLobidTest.java
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT000009600
- src/test/resources/jsonld/HT013304490
- src/test/resources/jsonld/HT017411546
- src/test/resources/output/json/00000/HT000009600.json
- src/test/resources/output/json/01330/HT013304490.json
- src/test/resources/output/json/01741/HT017411546.json
- src/test/resources/reverseTest/output/nt/00000/HT000009600.nt
- src/test/resources/reverseTest/output/nt/01330/HT013304490.nt
- src/test/resources/reverseTest/output/nt/01741/HT017411546.nt
Reverts hbz/lobid-resources#241
> Revert "Replace RDA for bibframe/supplement"

- web/app/controllers/resources/Application.java
Will resolve #270, resolve #271, and resolve #272.
> Fix issues with starred items

- web/app/views/details_item.scala.html
Will resolve https://github.com/hbz/lobid-resources/issues/287
> Update item details view for new properties

- web/conf/about.jsonld
> Add structured dataset description

- web/app/controllers/resources/Application.java
- web/app/controllers/resources/Index.java
- web/app/controllers/resources/Lobid.java
- web/app/views/query.scala.html
- web/app/views/tags/facets.scala.html
Will resolve https://github.com/hbz/lobid-resources/issues/306
> Add contributor facet

- web/app/views/tags/result_doc.scala.html
Will resolve https://github.com/hbz/lobid-resources/issues/316
> Display start and end dates in details page

- pom.xml
This reverts commit 02d5066cc4ff92b3e68f7a1f082ede5892809f7e.
Resolves #322.
> Revert "Remove unimportant library "jna""

- web/app/controllers/resources/Index.java
- web/test/tests/IntegrationTests.java
Will resolve https://github.com/hbz/lobid-resources/issues/197
> Hide temporary labels in API responses

- web/app/controllers/resources/Index.java
- web/test/tests/IntegrationTests.java
Will resolve https://github.com/hbz/lobid-resources/issues/327
> Fix regression introduced with 57b473b

- web/app/views/main.scala.html
Will partially resolve https://github.com/hbz/lobid/issues/323
> Update nav bar for new landing page

- web/app/controllers/resources/Application.java
Will resolve https://github.com/hbz/lobid-resources/issues/343
> Remove caching for API page

- web/app/views/api.scala.html
Will resolve https://github.com/hbz/lobid-resources/issues/279
> Add beta note to API documentation

- web/app/views/tags/result_doc.scala.html
- Use agent label for search links
- Don't show 'linked data source' link
Will resolve https://github.com/hbz/lobid-resources/issues/366
> Fix link issues for agents without IDs

- src/main/resources/labels/context-labels.json
- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/CT003012479
- src/test/resources/output/json/00301/CT003012479.json
- src/test/resources/reverseTest/output/nt/00301/CT003012479.nt
- web/conf/context.jsonld
> Remove dct source, rename key for isFormatOf

- web/app/views/api.scala.html
Will partially resolve https://github.com/hbz/lobid/issues/329
> Update API documentation

- web/app/views/api.scala.html
...as we do in the publication type facet.
> Use "Aufsatz" instead of "Artikel"

- src/main/resources/index-config.json
- web/app/controllers/resources/Application.java
- web/app/controllers/resources/Index.java
- web/app/controllers/resources/Lobid.java
- web/test/tests/AggregationsTest.java
Will resolve https://github.com/hbz/lobid-resources/issues/393
> Update field to use for subject facet

- web/app/views/TableRow.java
Will resolve https://github.com/hbz/lobid-resources/issues/409
> Handle missing `numbering` in `series`

- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT018781534
- src/test/resources/output/json/01878/HT018781534.json
- src/test/resources/reverseTest/output/nt/01878/HT018781534.nt
Take MAB 400 ("Ausgabebezeichnung in normierter Form"), if not existent 403 ("Ausgabebezeichnung in Vorlageform"), if both not existent take 510 ("Angaben zur Ausgabebezeichnung").
Resolves #415
> Add only one edition value

- src/main/resources/labels/labels.json
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT017411546
- src/test/resources/jsonld/HT018939763
- src/test/resources/jsonld/TT001966831
- src/test/resources/output/json/00196/TT001966831.json
- src/test/resources/output/json/01893/HT018939763.json
- src/test/resources/reverseTest/output/nt/00196/TT001966831.nt
- src/test/resources/reverseTest/output/nt/01893/HT018939763.nt
> Add some missing languages

- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT015894164
- src/test/resources/jsonld/HT018700720
- src/test/resources/jsonld/HT018895767
- src/test/resources/jsonld/HT019011249
- src/test/resources/jsonld/TT001230001
- src/test/resources/output/json/00123/TT001230001.json
- src/test/resources/output/json/01589/HT015894164.json
- src/test/resources/output/json/01870/HT018700720.json
- src/test/resources/output/json/01889/HT018895767.json
- src/test/resources/output/json/01901/HT019011249.json
- src/test/resources/reverseTest/output/nt/00123/TT001230001.nt
- src/test/resources/reverseTest/output/nt/01589/HT015894164.nt
- src/test/resources/reverseTest/output/nt/01870/HT018700720.nt
- src/test/resources/reverseTest/output/nt/01889/HT018895767.nt
- src/test/resources/reverseTest/output/nt/01901/HT019011249.nt
> Define resources with MAB 051s as books

- web/app/controllers/resources/Accept.java
- web/app/controllers/resources/Application.java
- web/app/controllers/resources/Lobid.java
- web/app/controllers/resources/RdfConverter.java
- web/app/views/api.scala.html
- web/app/views/details.scala.html
- web/app/views/query.scala.html
- web/app/views/tags/query_result_short.scala.html
- web/build.sbt
- web/conf/resources.conf
- web/conf/resources.routes
- web/test/tests/AcceptIntegrationTest.java
- web/test/tests/AcceptUnitTest.java
- web/test/tests/RdfConverterTests.java
Will resolve https://github.com/hbz/lobid-resources/issues/454
> Support RDF content types in single document GET requests

- src/main/java/org/lobid/resources/Stats.java
- src/main/java/org/lobid/resources/run/MakeStatisticsMabXml.java
- src/main/resources/morph-makeHbz01Statistics.xml
After "mvn clean install", run like this:
`$ mvn exec:java -Dexec.mainClass="org.lobid.resources.run.MakeStatisticsMabXml" -Dexec.args="src/test/resources/hbz01XmlClobs.tar.bz2"`.
Adapt morph-makeHbz01Statistics.xml till it suits you well.
Resolves #466.
> Add example how to make statistics about hbz01

- src/main/java/org/lobid/resources/run/MabXml2lobidJsonEs.java
- src/main/resources/morph-hbz01-to-lobid.xml
> Remove creation of statistics when transforming hbz01

- src/main/resources/morph-hbz01-to-lobid.xml
- src/main/resources/morph-makeHbz01Statistics.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT003654516
- src/test/resources/jsonld/HT004944075
- src/test/resources/jsonld/HT005944358
- src/test/resources/jsonld/HT012996101
- src/test/resources/jsonld/HT015082724
- src/test/resources/jsonld/TT001966831
- src/test/resources/output/json/00196/TT001966831.json
- src/test/resources/output/json/00365/HT003654516.json
- src/test/resources/output/json/00494/HT004944075.json
- src/test/resources/output/json/00594/HT005944358.json
- src/test/resources/output/json/01299/HT012996101.json
- src/test/resources/output/json/01508/HT015082724.json
- src/test/resources/reverseTest/output/nt/00196/TT001966831.nt
- src/test/resources/reverseTest/output/nt/00365/HT003654516.nt
- src/test/resources/reverseTest/output/nt/00494/HT004944075.nt
- src/test/resources/reverseTest/output/nt/00594/HT005944358.nt
- src/test/resources/reverseTest/output/nt/01299/HT012996101.nt
- src/test/resources/reverseTest/output/nt/01508/HT015082724.nt
> Remove zdb-link to superordinate if lobid-link exists

- src/main/java/org/lobid/resources/ElasticsearchIndexer.java
The method "aliases(String name)" is called two times. While the first call,
used by renaming aliases, is working fine, the second call (deleting old
indices) is not working. The logs showed:
"[WARNING] thread Thread[elasticsearch[Electron][scheduler]"
resulting in an java.lang.IllegalThreadStateException.
DEBUG level shows that NIO is involved:
("Selector.select() returned prematurely because the I/O thread has been interrupted. Use shutdown() to shut the NioSelector down).
However, checking if an alias is set for a given index is what is needed.
This can also be achieved by:
"getMetaData().hasAliases(new String[] { "*" }, new String[] { indexToDelete })"
where two string arrays are the parameters. There is also a method
"hasAlias(String name)" not needing that array, but then this …
> Delete all indices without alias

- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/jsonld/HT004381366
- src/test/resources/output/json/00438/HT004381366.json
- src/test/resources/reverseTest/output/nt/00438/HT004381366.nt
> Separate superordinate componentList

- web/app/views/api.scala.html
See https://github.com/hbz/lobid/issues/345
> Remove open beta notice

- web/app/controllers/resources/Lobid.java
Will resolve https://github.com/hbz/lobid-resources/issues/340
> Fix confusing labels in owner facet

- src/main/resources/labels/context-labels.json
- web/conf/context.jsonld
See #427 
(For example https://github.com/hbz/lobid-resources/issues/427#issuecomment-307040729)
> Remove volumeIn from context

- web/app/views/TableRow.java
- web/app/views/tags/result_doc.scala.html
Will resolve https://github.com/hbz/lobid-resources/issues/512
> Handle isPartOf with no hasSuperordinate.id and no numbering

- web/app/views/dataset.scala.html
- web/conf/dataset.jsonld
Fixes https://github.com/hbz/lobid-resources/issues/498
> Add link to source data in dataset description

- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT001898812
- src/test/resources/jsonld/HT013056453
- src/test/resources/jsonld/HT015090208
- src/test/resources/jsonld/HT016382441
- src/test/resources/jsonld/HT016556189
- src/test/resources/jsonld/HT016604323
- src/test/resources/jsonld/HT017411546
- src/test/resources/jsonld/HT018939763
- src/test/resources/jsonld/TT000075751
- src/test/resources/output/json/00007/TT000075751.json
- src/test/resources/output/json/00189/HT001898812.json
- src/test/resources/output/json/01305/HT013056453.json
- src/test/resources/output/json/01509/HT015090208.json
- src/test/resources/output/json/01638/HT016382441.json
- src/test/resources/output/json/01655/HT016556189.json
- src/test/resources/output/json/01660/HT016604323.json
- src/test/resources/output/json/01893/HT018939763.json
- src/test/resources/reverseTest/output/nt/00007/TT000075751.nt
- src/test/resources/reverseTest/output/nt/00189/HT001898812.nt
- src/test/resources/reverseTest/output/nt/01305/HT013056453.nt
- src/test/resources/reverseTest/output/nt/01509/HT015090208.nt
- src/test/resources/reverseTest/output/nt/01638/HT016382441.nt
- src/test/resources/reverseTest/output/nt/01655/HT016556189.nt
- src/test/resources/reverseTest/output/nt/01660/HT016604323.nt
- src/test/resources/reverseTest/output/nt/01893/HT018939763.nt
> 461 improve publication type definition

- src/main/resources/labels/context-labels.json
- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT019149667
- src/test/resources/output/json/01914/HT019149667.json
- src/test/resources/reverseTest/output/nt/01914/HT019149667.nt
- web/conf/context.jsonld
> Add "RPB-Raumsystematik" as a source, remove it from other RPB subjects

- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT003536695
- src/test/resources/jsonld/HT016618741
- src/test/resources/jsonld/HT018468645
- src/test/resources/jsonld/HT019011249
- src/test/resources/output/json/00353/HT003536695.json
- src/test/resources/output/json/01661/HT016618741.json
- src/test/resources/output/json/01846/HT018468645.json
- src/test/resources/output/json/01901/HT019011249.json
- src/test/resources/reverseTest/output/nt/00353/HT003536695.nt
- src/test/resources/reverseTest/output/nt/01661/HT016618741.nt
- src/test/resources/reverseTest/output/nt/01846/HT018468645.nt
- src/test/resources/reverseTest/output/nt/01901/HT019011249.nt
Resolves https://github.com/lobid/lodmill/issues/489
> Expand definition of fulltextOnlineUri, DOI and URN labels

- src/main/resources/labels/labels.json
> Change label "Alternative Energiequelle" -> "Erneuerbare Energien"

- src/main/java/org/lobid/resources/ElasticsearchIndexer.java
When a fallback geodata-lookup was done once for a query the lookup
should not be done for the same query again being in the same transformtion
session, because when the query fails at the first time it will most probably
fail subsequently.
This does not only prevent repeating lookups of failed queries but also of
successfully queries which were stored in the geodata-elasticsearch-index
but which scores not enough so that the fallback lookup would be done
repeatedly.
See #579.
> Avoid unnecessary fallback-lookups

- src/main/java/org/lobid/resources/run/WikidataGeodata2Es.java
- src/main/resources/getNwbibSubjectLocationsAsWikidataEntities.txt
- src/test/resources/jsonld/HT013077595
- index wd-entities even if they have no geo-coordinates
See #585.
> Decrease SPARQ limit; catch more exceptions

- src/main/java/org/lobid/resources/ElasticsearchIndexer.java
- src/main/java/org/lobid/resources/run/MabXml2lobidJsonEs.java
- src/main/java/org/lobid/resources/run/WikidataGeodata2Es.java
- src/main/resources/getNwbibSubjectLocationsAsWikidataEntities.txt
Incorporates the superordinated "locatedIn" into the geo-cache.
The label of the "locatedIn" is down-boosted with a factor of `0.3`. Compare this with a boost for "label" of `5.0` and "aliases" with no boost.
We will see if these boosts make sense when fulldump-data is deployed on monday
See #585.
> 585 improve geodata lookup2

- src/main/resources/labels/context-labels.json
- web/conf/context.jsonld
Fixes https://github.com/hbz/lobid-resources/issues/570
> Remove obsolete properties from JSON -LD context

- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT004381366
- src/test/resources/output/json/00438/HT004381366.json
- src/test/resources/reverseTest/output/nt/00438/HT004381366.nt
See https://github.com/hbz/lobid-resources/issues/585#issuecomment-338651804
> Remove non-administrative areas from "coverage"

- src/main/java/org/lobid/resources/ElasticsearchIndexer.java
- add MultiMatchQueryBuilder.Type.CROSS_FIELDS
- fix path of "aliases" and "locatedInd"
- tweak boost of fields
- increase MINIMUM_SCORE
See #585.
> Improve geo matching

- .classpath
- src/main/resources/index-config.json
- src/test/resources/hbz01.es.nt
- web/app/controllers/resources/Index.java
- web/app/controllers/resources/Lobid.java
- web/build.sbt
- web/project/build.properties
For NWBib faceted search, see https://github.com/hbz/nwbib/issues/163
> Add aggregations support for additional fields

- src/main/java/org/lobid/resources/run/WikidataGeodata2Es.java
- src/main/resources/index-config-wd-geodata.json
- src/main/resources/index-config.json
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/BT000041593
- src/test/resources/jsonld/BT000067443
- src/test/resources/jsonld/BT000128754
- src/test/resources/jsonld/HT013077595
- src/test/resources/jsonld/HT014319164
- src/test/resources/jsonld/HT018239864
- src/test/resources/jsonld/HT018612706
- src/test/resources/jsonld/TT003060418
- remove type "GeoCoordinates"
- adapt index-config
Resolves #601.
> Make geo data elasticsearch compatible

- web/app/controllers/resources/Application.java
- web/app/controllers/resources/Index.java
- web/conf/resources.routes
- web/test/tests/InputStringsTest.java
- web/test/tests/IntegrationTests.java
Deployed to stage:
http://stage.lobid.org/resources/search?q=*&format=json&aggregations=spatial.geo
http://stage.lobid.org/resources/search?q=*&format=json&location=50.94218730926514,6.957736015319824
@dr0i: No transformation or index deployment required, just for review.
See https://github.com/hbz/nwbib/issues/163
>  Support aggregation and location search based on `spatial.geo` field

- src/main/java/org/lobid/resources/ElasticsearchIndexer.java
> Tweak scoring of field "alias"

- src/main/resources/labels/context-labels.json
- src/test/java/org/lobid/resources/AbstractIngestTests.java
- src/test/resources/hbz01.es.nt
- web/conf/context.jsonld
> Add geo properties to context

- src/main/java/org/lobid/resources/ElasticsearchIndexer.java
- src/test/resources/jsonld/HT013077595
> Ensure unique spatial entries

- src/main/resources/labels/context-labels.json
- src/test/resources/hbz01.es.nt
Fixes https://github.com/hbz/lobid-resources/issues/618
> Remove redundant entries in context-labels.json

- web/app/views/TableRow.java
Will resolve https://github.com/hbz/lobid-resources/issues/633
> Fix details view for non-URL titles starting with `http`

- src/main/resources/getNwbibSubjectLocationsAsWikidataEntities.txt
Fixes https://github.com/hbz/lobid-resources/issues/631
> Add missing types to Wikidata SPARQL query

- web/app/Global.java
- web/app/controllers/resources/Index.java
- web/app/controllers/resources/LocalIndex.java
- web/conf/resources.conf
- web/test/tests/LocalIndexSetup.java
Will resolve https://github.com/hbz/lobid-resources/issues/286
Based on the ES 5.6 code base.
> Support using embedded test index for UI

- web/conf/application.conf
- web/conf/logback.xml
Application log-level was not set to DEBUG but that was in fact used.
Using logback.xml fixes this.
Also, this comes with a FileRoller. Should roll every week.
> Fix logging config for Play

- web/app/views/details.scala.html
- web/app/views/tags/result_doc.scala.html
Will resolve https://github.com/hbz/lobid-resources/issues/383
See http://stage.lobid.org/resources/HT016132955
> Display `corporateBodyForTitle` as part of title

- web/app/views/tags/items_map.scala.html
Will resolve https://github.com/hbz/lobid-resources/issues/167
See http://stage.lobid.org/resources/HT010613475
> Show item `note` field in UI

- web/app/views/tags/result_doc.scala.html
Will resolve https://github.com/hbz/lobid-resources/issues/542
See:
http://stage.lobid.org/resources/HT005626958 (no dates)
http://stage.lobid.org/resources/HT005067303 (dates)
> Fix display of publications without start or end date

- src/main/resources/index-config.json
Resolves https://github.com/hbz/lobid-resources/issues/684
> Adjust index-config for frequency

- src/main/java/org/lobid/resources/ElasticsearchIndexer.java
> Set replica to 0 only when creating new index

- src/main/resources/morph-hbz01-to-lobid.xml
> 690 force label to be literal

- src/main/java/org/lobid/resources/Triples2RdfModel.java
Generating triples via the morph sometimes results in invalid triples, e.g.
when URIs are invalid, e.g. consist of `<`. To date the parsing execption of
such resource resulted in the dropping of the complete document with all their
triples, even when te other triples were fine. Now, only the invalid triples are
dropped. Log-messages are written so that at a later stage the moprh can be
adjusted to produce valid triples.
See e.g. #536.
> Improve rdf-parsing by dropping invalid triples

- web/app/views/TableRow.java
Partially resolves https://github.com/hbz/lobid-resources/issues/718
> Avoid null pointer on empty objects

- src/main/resources/labels/labels.json
See https://github.com/hbz/lobid-vocabs/pull/78
> Add new RPB classification concept

- web/app/controllers/resources/Queries.java
Will resolve https://github.com/hbz/lobid-resources/issues/717
> Fix agent-by-id queries

- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT007847893
- src/test/resources/jsonld/HT013056453
- src/test/resources/jsonld/HT014525099
- src/test/resources/jsonld/HT016608165
- src/test/resources/jsonld/HT017411546
- src/test/resources/jsonld/HT019149667
- src/test/resources/jsonld/TT000075751
- src/test/resources/jsonld/TT001230001
- src/test/resources/output/json/00007/TT000075751.json
- src/test/resources/output/json/00123/TT001230001.json
- src/test/resources/output/json/00306/TT003060418.json
- src/test/resources/output/json/00784/HT007847893.json
- src/test/resources/output/json/01452/HT014525099.json
- src/test/resources/output/json/01660/HT016608165.json
- src/test/resources/output/json/01741/HT017411546.json
- src/test/resources/output/json/01861/HT018612706.json
- src/test/resources/output/json/01914/HT019149667.json
- src/test/resources/reverseTest/output/nt/00007/TT000075751.nt
- src/test/resources/reverseTest/output/nt/00123/TT001230001.nt
- src/test/resources/reverseTest/output/nt/00784/HT007847893.nt
- src/test/resources/reverseTest/output/nt/01452/HT014525099.nt
- src/test/resources/reverseTest/output/nt/01660/HT016608165.nt
- src/test/resources/reverseTest/output/nt/01861/HT018612706.nt
- src/test/resources/reverseTest/output/nt/01914/HT019149667.nt
Resolves https://github.com/hbz/lobid-resources/issues/516
> Add also work titles from MAB 304b

- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT018612706
- src/test/resources/jsonld/HT019149667
- src/test/resources/output/json/01330/HT013304490.json
- src/test/resources/output/json/01741/HT017411546.json
- src/test/resources/output/json/01914/HT019149667.json
- src/test/resources/reverseTest/output/nt/01330/HT013304490.nt
- src/test/resources/reverseTest/output/nt/01914/HT019149667.nt
> Remove superflous code

- web/app/controllers/resources/Queries.java
- web/app/views/tags/result_doc.scala.html
@acka47: assigning PR for functional review since we have no dedicated issue.
Group subjects in details view by their source: http://stage.lobid.org/resources/HT019570509
> Changes related to NWBib switch to API 2

- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT005944358
- src/test/resources/jsonld/HT012996101
- src/test/resources/jsonld/HT015455455
- src/test/resources/jsonld/HT017411546
- src/test/resources/jsonld/HT018138676
- src/test/resources/output/json/00306/TT003060418.json
- src/test/resources/output/json/00594/HT005944358.json
- src/test/resources/output/json/01299/HT012996101.json
- src/test/resources/output/json/01545/HT015455455.json
- src/test/resources/output/json/01813/HT018138676.json
- src/test/resources/reverseTest/output/nt/00594/HT005944358.nt
- src/test/resources/reverseTest/output/nt/01299/HT012996101.nt
- src/test/resources/reverseTest/output/nt/01545/HT015455455.nt
- src/test/resources/reverseTest/output/nt/01813/HT018138676.nt
Resolves https://github.com/hbz/lobid-resources/issues/638
> Add MAB 375e to alternative title

- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/jsonld/TT003060418
- src/test/resources/output/json/00306/TT003060418.json
- src/test/resources/output/json/01741/HT017411546.json
Resolves https://github.com/hbz/lobid-resources/issues/742
> Remove sharp brackets from creation of containsExampleOfWork bnode

- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/BT000128754
- src/test/resources/jsonld/HT017411546
- src/test/resources/output/json/00012/BT000128754.json
- src/test/resources/reverseTest/output/nt/00012/BT000128754.nt
Resolves https://github.com/hbz/lobid-resources/issues/590
> Correct regular expression for containedIn

- web/app/views/details.scala.html
Will resolve https://github.com/hbz/lobid-resources/issues/768
> Use first element of `otherTitleInformation` as subtitle

- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT000009600
- src/test/resources/jsonld/HT002619538
- src/test/resources/jsonld/HT010726584
- src/test/resources/jsonld/HT013056453
- src/test/resources/jsonld/HT016138627
- src/test/resources/output/json/00000/HT000009600.json
- src/test/resources/output/json/00261/HT002619538.json
- src/test/resources/output/json/01072/HT010726584.json
- src/test/resources/output/json/01305/HT013056453.json
- src/test/resources/output/json/01613/HT016138627.json
- src/test/resources/reverseTest/output/nt/00000/HT000009600.nt
- src/test/resources/reverseTest/output/nt/00261/HT002619538.nt
- src/test/resources/reverseTest/output/nt/01072/HT010726584.nt
- src/test/resources/reverseTest/output/nt/01305/HT013056453.nt
- src/test/resources/reverseTest/output/nt/01613/HT016138627.nt
Resolves https://github.com/hbz/lobid-resources/issues/775
> Add missing hbz-URLs to predecessor and successor

- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT015090208
- src/test/resources/jsonld/HT016556189
- src/test/resources/jsonld/HT017066705
- src/test/resources/output/json/01509/HT015090208.json
- src/test/resources/output/json/01655/HT016556189.json
- src/test/resources/output/json/01706/HT017066705.json
- src/test/resources/reverseTest/output/nt/01509/HT015090208.nt
- src/test/resources/reverseTest/output/nt/01655/HT016556189.nt
- src/test/resources/reverseTest/output/nt/01706/HT017066705.nt
Resolves https://github.com/hbz/lobid-resources/issues/779
> Expand definition of extent

- web/app/controllers/resources/Application.java
- web/app/controllers/resources/Deletions.java
- web/app/views/api.scala.html
- web/conf/resources.routes
> Add controller to access the "deletion" index

- web/app/views/api.scala.html
Will resolve https://github.com/hbz/lobid-resources/issues/801
> Update deletions API sample

- src/main/java/org/lobid/resources/ElasticsearchIndexer.java
- src/main/java/org/lobid/resources/RecordReaderEnhanced.java
- src/main/java/org/lobid/resources/run/Entityfacts2Es.java
- src/main/resources/index-config-entityfacts.json
Splits the line separated json of the entityfacts dump, gets the GND-ID as the
internal ID of ES and index the records as bulk into ES on our cluster.
Resolves hbz/lobid-gnd#44.
> Build new index entityfacts

- src/main/java/org/lobid/resources/run/WikidataGeodata2Es.java
- src/main/resources/index-config-wd-geodata.json
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/BT000041593
- src/test/resources/jsonld/BT000067443
- src/test/resources/jsonld/BT000128754
- src/test/resources/jsonld/HT013077595
- src/test/resources/jsonld/HT014319164
- src/test/resources/jsonld/HT017411546
- src/test/resources/jsonld/HT018239864
> 807 add wikidata type

- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT003654516
- src/test/resources/jsonld/HT004944075
- src/test/resources/jsonld/HT005944358
- src/test/resources/jsonld/HT012996101
- src/test/resources/jsonld/HT015082724
- src/test/resources/jsonld/TT001966831
- src/test/resources/output/json/00196/TT001966831.json
- src/test/resources/output/json/00365/HT003654516.json
- src/test/resources/output/json/00494/HT004944075.json
- src/test/resources/output/json/00594/HT005944358.json
- src/test/resources/output/json/01299/HT012996101.json
- src/test/resources/output/json/01508/HT015082724.json
- src/test/resources/output/json/01741/HT017411546.json
- src/test/resources/reverseTest/output/nt/00196/TT001966831.nt
- src/test/resources/reverseTest/output/nt/00365/HT003654516.nt
- src/test/resources/reverseTest/output/nt/00494/HT004944075.nt
- src/test/resources/reverseTest/output/nt/00594/HT005944358.nt
- src/test/resources/reverseTest/output/nt/01299/HT012996101.nt
- src/test/resources/reverseTest/output/nt/01508/HT015082724.nt
- web/conf/context.jsonld
> Improve regular expression

- src/main/java/org/lobid/resources/ElasticsearchIndexer.java
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/BT000128754
- src/test/resources/jsonld/HT014319164
- src/test/resources/jsonld/HT018239864
> Make enrichment query of geo type mandatory

- web/app/controllers/resources/Queries.java
Will resolve https://github.com/hbz/lobid-resources/issues/832
> Boost title fields in all-field queries

- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT000052280
- src/test/resources/output/json/00005/HT000052280.json
- src/test/resources/reverseTest/output/nt/00005/HT000052280.nt
- web/conf/context.jsonld
> Use MAB 003 for dateCreated if no dateCreated exists

- src/main/resources/index-config.json
> Also index label of exampleOfWork

- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/BT000040377
- src/test/resources/jsonld/BT000103077
- src/test/resources/jsonld/BT000110055
- src/test/resources/jsonld/HT018612706
- src/test/resources/output/json/00004/BT000040377.json
- src/test/resources/output/json/00010/BT000103077.json
- src/test/resources/output/json/00011/BT000110055.json
- src/test/resources/output/json/01861/HT018612706.json
- src/test/resources/reverseTest/output/nt/00004/BT000040377.nt
- src/test/resources/reverseTest/output/nt/00010/BT000103077.nt
- src/test/resources/reverseTest/output/nt/00011/BT000110055.nt
> 669 missing entries in old nw bib subjects

- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/jsonld/HT007015768
- src/test/resources/jsonld/HT017411546
- src/test/resources/jsonld/HT018612706
- src/test/resources/output/json/00701/HT007015768.json
- src/test/resources/output/json/01741/HT017411546.json
- src/test/resources/output/json/01861/HT018612706.json
- src/test/resources/reverseTest/output/nt/00701/HT007015768.nt
> Add missing agent to resources with MAB 342 etc.

- web/app/controllers/resources/Accept.java
- web/app/controllers/resources/Application.java
- web/app/views/api.scala.html
- web/test/tests/IntegrationTests.java
Will resolve https://github.com/hbz/lobid-resources/issues/861
> Alias `jsonl` format param for bulk downloads

- web/monit_restart.sh
- web/restart.sh
This may prevent some monit restart problems.
See mail "Lobid-resources web app unerreichbar für 5 Stunden"
from Fri, 27 Jul 2018 11:46:07 +0200 to lobid-admin.
Message ID: <0ef83206-bffb-418d-a847-aa728f9a1c21@hbz-nrw.de>
> Ensure killing of web app

- src/main/resources/index-config.json
- src/main/resources/morph-hbz01-to-lobid.xml
- remove unused secondaryPublication index config
Resolves #873.
> Use date for publication.startDate and publication.endDate

- src/main/resources/index-config-deletions.json
> Change field type of describedBy.deleted to "date"

- web/app/controllers/resources/Accept.java
- web/app/controllers/resources/Application.java
- web/app/views/api.scala.html
- web/app/views/main.scala.html
- web/app/views/query.scala.html
- web/app/views/rss.scala.html
- web/conf/resources.conf
- web/test/tests/AcceptIntegrationTest.java
- web/test/tests/AcceptUnitTest.java
- web/test/tests/IntegrationTests.java
> Support RSS as response format for search requests

- src/main/java/org/lobid/resources/run/WikidataGeodata2Es.java
- src/main/resources/getNwbibSubjectLocationsAsWikidataEntities.sparql
Covering the problems mentioned in https://github.com/hbz/lobid-resources/issues/585#issuecomment-419824099 & https://github.com/hbz/lobid-resources/issues/585#issuecomment-419843537
> Improve matching

- web/app/views/dataset.scala.html
- web/app/views/main.scala.html
- web/conf/dataset.jsonld
Resolves #913. We will probably have to fix some things for the HTML view before deploying, thus assigning @fsteeg .
> Update dataset description

- web/app/controllers/resources/Application.java
- web/app/views/error.scala.html
Will resolve https://github.com/hbz/lobid-resources/issues/921
> Display error message for invalid queries

- src/main/java/org/lobid/resources/ElasticsearchIndexer.java
This ensures an overwrite of updated documents rather then a merge.
Resolves #928.
> Switch to "insert" instead of "upsert"

- pom.xml
- src/main/java/org/lobid/resources/ElasticsearchIndexer.java
- src/main/java/org/lobid/resources/run/MabXml2lobidJsonEs.java
- src/main/java/org/lobid/resources/run/WikidataGeodata2Es.java
- src/test/resources/buildAndETLTestSet.sh
- startHbz01ToLobidResources.sh
Fixes `org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: no settings to update;`.
> Fix update settings

- src/main/resources/string2wikidata.tsv
...as requested by NWBib customer I.N. via email on 2018-10-12.
> Map last region strings to Wikidata

- pom.xml
- src/main/java/de/hbz/lobid/helper/JsonConverter.java
- src/test/resources/hbz01.es.nt
- web/conf/context.jsonld
Will resolve https://github.com/hbz/lobid-resources/issues/938
> Update Jackson dependency

- web/app/controllers/resources/Application.java
- web/test/tests/IntegrationTests.java
See https://github.com/hbz/lobid-resources/issues/830
> Avoid internal URL in JSON response

- pom.xml
- web/app/controllers/resources/Search.java
For number of hits in Raumsystematik
Required to resolve hbz/nwbib#397
>  Add spatial.id to supported aggregations 

- web/app/controllers/resources/Search.java
For hit counts in Sachsystematik
See https://github.com/hbz/nwbib/issues/453
> Increase aggregation size for subject ID

- src/main/java/org/lobid/resources/ElasticsearchIndexer.java
- src/main/java/org/lobid/resources/run/UpdateAliases.java
- rename variables
- mark important key words in log messages
Resolves #994.
> Fix comparing of deletions

- src/main/java/org/lobid/resources/run/WikidataGeodata2Es.java
See https://github.com/hbz/lobid-resources/pull/1020#pullrequestreview-287883185.
> Use more elagant way to load lines of a file

- startHbz01ToLobidResources.sh
> Ensure to clean-assemble java project only once

- web/app/views/api.scala.html
> Add aggregations example to api description

- web/conf/context.jsonld
Fixes https://github.com/hbz/lobid-resources/issues/1053
@dr0i, please merge and deploy.
> Add hydra properties to JSON-LD context

- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT019474284
> Normalize similar.isbn

- src/main/resources/labels/labels.json
- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/CT001004829
- src/test/resources/jsonld/CT003012479
- src/test/resources/jsonld/HT003536695
- src/test/resources/jsonld/HT006698544
- src/test/resources/jsonld/HT009719670
- src/test/resources/jsonld/HT013532539
- src/test/resources/jsonld/HT017411546
- src/test/resources/jsonld/HT018138676
- src/test/resources/jsonld/HT018260267:DE-6:43-1-3411,2014
- src/test/resources/jsonld/HT018290299
- src/test/resources/jsonld/HT018786244
- src/test/resources/jsonld/HT020015895
- src/test/resources/jsonld/TT050409948
> Add collections also when not an Isil

- src/main/resources/labels/labels.json
As proposed in https://github.com/hbz/lobid-resources/issues/1052#issuecomment-600000152 f, I removed spaces and ampersands from the IDs.
> Add more labels for non-ISIL packages

- src/main/resources/string2wikidata.tsv
...to correct the links as in https://github.com/hbz/nwbib/issues/541
> Add Werne in string2wikidata.tsv for ZDB resources

- scripts/getAllData.sh
See https://github.com/hbz/lobid-resources/issues/1048.
> Add script to dump the data

- web/app/views/api.scala.html
See https://github.com/hbz/lobid-resources/issues/1073.
Done analog to https://lobid.org/gnd/api#bulk_downloads.
> Document bulk download

- src/main/resources/beacon/data/beacon_head.txt
- src/main/resources/beacon/makePndBeacon.sh
> 1075 fix gnd beacon

- web/app/controllers/resources/Queries.java
- web/test/tests/IndexIntegrationTest.java
See https://github.com/hbz/nwbib/issues/554
Deployed to test, forgot it's currently production, so this is already deployed to production.
See https://nwbib.de/search?q=%22Fiktionale+Darstellung%22
> Add natureOfContent.label to word query

- web/app/controllers/resources/Application.java
- web/app/views/main.scala.html
- web/app/views/query.scala.html
- web/app/views/tags/facets.scala.html
- web/app/views/tags/search_form.scala.html
See https://github.com/hbz/lobid/issues/423
> Improve accessibility for lobid-resources

- web/conf/context.jsonld
This should resolve #1083 #1084 #1098 if the context plays a role in generation of the JSON-LD output. @dr0i, can you please take over here?
> Update context to enforce array for some properties

- src/main/resources/alma/common/item.xml
- src/main/resources/labels/context-labels.json
- src/test/resources/alma/HT005207972.json
- src/test/resources/alma/HT012734833.json
- src/test/resources/alma/HT012734884.json
- src/test/resources/alma/HT016709661.json
- src/test/resources/alma/HT017664407.json
- src/test/resources/alma/KUR00770801.json
- src/test/resources/schemas/hasItem.json
- web/conf/context.jsonld
This worked out faster than I thought.
> Add POR-data to heldBy (#1116)

- src/main/resources/morph-hbz01-to-lobid.xml
- src/test/resources/hbz01.es.nt
- src/test/resources/jsonld/HT015894164.json
> 1125 fix zdb id parsing

- src/main/java/org/lobid/resources/JsonToElasticsearchBulkMap.java
- src/main/java/org/lobid/resources/run/AlmaMarcXml2lobidJsonEs.java
- startAlmaToLobidResources.sh
Doing the full ETL process, using 6 threads.
- add start script used by crontab
See #1112.
> Index Alma lobid JSON into ES

- src/main/resources/index-config.json
> Add "electronicLocator" and "sublocation" to index profile

- src/main/resources/alma/common/fields.xml
- src/test/resources/alma/(DE-605)HT005207972.json
- src/test/resources/alma/(DE-605)HT012734833.json
- src/test/resources/alma/(DE-605)HT012734884.json
- src/test/resources/alma/(DE-605)HT020391499.json
- src/test/resources/alma/HT016709661.json
- src/test/resources/alma/HT017664407.json
> 1140 change hbzId

- src/main/resources/alma/common/item.xml
- src/main/resources/alma/maps.xml
- src/main/resources/alma/maps/alma-iz-code-to-isil.xml
- src/test/resources/alma/(DE-605)HT005207972.json
- src/test/resources/alma/(DE-605)HT012734833.json
- src/test/resources/alma/(DE-605)HT012734884.json
- src/test/resources/alma/(DE-605)HT020391499.json
- src/test/resources/alma/HT016709661.json
- src/test/resources/alma/HT017664407.json
If POR$$A exists it's the holder of this Item.
- add a new map alma-iz-code-to-isil to map between iz code to isil
- add 'POR  .A' to morph and precedence it over 'POR  .a'
See #1145.
> Add alma-iz-code-to-isil and precedence POR$$A as Item holder

- src/main/resources/alma/common/describedBy.xml
- src/test/resources/alma/(DE-605)HT012734833.json
- src/test/resources/alma/HT016709661.json
- src/test/resources/alma/HT017664407.json
> Exclude 9999 and 0001 as modifiing agency

- src/main/resources/index-config.json
> Add almaIdMMS to index-profile

- src/main/resources/alma/common/fields.xml
- src/test/resources/alma/(DE-605)HT017398609.json
> Delete not sorting signs in title (#1156)

- .github/workflows/build.yml
- src/main/java/de/hbz/lobid/helper/Email.java
- src/main/java/org/lobid/resources/run/AlmaMarcXml2lobidJsonEs.java
- src/main/java/org/lobid/resources/run/UpdateAliases.java
- web/app/Global.java
- web/app/controllers/resources/Webhook.java
- web/build.sbt
- web/conf/resources.conf
- web/conf/resources.routes
See #1159.
Further desiderate:
Also enable GET, not only POST.
> 1159 webhook listener 1

- src/main/resources/alma/common/item.xml
- src/test/resources/alma/(CKB)2560000000104439.json
- src/test/resources/alma/(CKB)2560000000104439.xml
- src/test/resources/alma/(DE-605)HT020391499.json
- src/test/resources/alma/HT016709661.json
- src/test/resources/alma/HT017664407.json
- src/test/resources/alma/updateAlmaTestFiles.sh
> 1158 take all "POR A" into account 

- src/main/resources/alma/common/item.xml
- src/test/resources/alma/(DE-605)HT006855611.json
- src/test/resources/alma/(DE-605)HT006855611.xml
I think I have a solution for #1174 .
This PR should replace #1185.
> 1174 include ho lwithout itm working

- src/main/resources/alma/common/fields.xml
- src/test/resources/alma/(DE-605)HT019246898.json
See #1180 
I needed to update the old testfiles first and then add the unique function to the ISBN transformation.
https://github.com/hbz/lobid-resources/issues/1180#issuecomment-815504138
> 1180 deduplicate isbn

- src/main/resources/alma/common/contribution.xml
- src/test/resources/alma/(CKB)2560000000104439.json
- src/test/resources/alma/(DE-605)HT000161712.json
- src/test/resources/alma/(DE-605)HT005207972.json
- src/test/resources/alma/(DE-605)HT006855611.json
- src/test/resources/alma/(DE-605)HT012734884.json
- src/test/resources/alma/(DE-605)HT015671602.json
- src/test/resources/alma/(DE-605)HT016709661.json
- src/test/resources/alma/(DE-605)HT017398609.json
- src/test/resources/alma/(DE-605)HT019246898.json
- src/test/resources/alma/(DE-605)HT020202475.json
- src/test/resources/alma/(DE-605)HT020391499.json
> Add responsibility statement

- src/main/resources/alma/common/subjects.xml
- src/test/resources/alma/(DE-605)HT000161712.json
- src/test/resources/alma/(DE-605)HT005207972.json
- src/test/resources/alma/(DE-605)HT006855611.json
- src/test/resources/alma/(DE-605)HT012734884.json
- src/test/resources/alma/(DE-605)HT015671602.json
- src/test/resources/alma/(DE-605)HT016709661.json
- src/test/resources/alma/(DE-605)HT017664407.json
- src/test/resources/alma/(DE-605)HT019246898.json
- src/test/resources/alma/(DE-605)HT020202475.json
- src/test/resources/alma/(OCoLC)1073526105.json
> 1190 subject alt label

- src/main/resources/alma/common/facets.xml
- src/test/resources/alma/(DE-605)HT012734884.json
> Combine the two instances of "periodical" in one (#1136)

- src/main/resources/alma/common/fields.xml
- src/test/resources/alma/(CKB)2560000000104439.json
- src/test/resources/alma/(DE-605)HT000161712.json
- src/test/resources/alma/(DE-605)HT005207972.json
- src/test/resources/alma/(DE-605)HT006855611.json
- src/test/resources/alma/(DE-605)HT012734833.json
- src/test/resources/alma/(DE-605)HT012734884.json
- src/test/resources/alma/(DE-605)HT015671602.json
- src/test/resources/alma/(DE-605)HT016709661.json
- src/test/resources/alma/(DE-605)HT017015300.json
- src/test/resources/alma/(DE-605)HT017398609.json
- src/test/resources/alma/(DE-605)HT017664407.json
- src/test/resources/alma/(DE-605)HT019246898.json
- src/test/resources/alma/(DE-605)HT020202475.json
- src/test/resources/alma/(DE-605)HT020391499.json
- src/test/resources/alma/(OCoLC)1073526105.json
> Change "publication" mapping to separate entries (#1138)

- src/main/resources/alma/common/subjects.xml
- src/test/resources/alma/(DE-605)HT000161712.json
- src/test/resources/alma/(DE-605)HT005207972.json
- src/test/resources/alma/(DE-605)HT006855611.json
- src/test/resources/alma/(DE-605)HT012734884.json
- src/test/resources/alma/(DE-605)HT015671602.json
- src/test/resources/alma/(DE-605)HT016709661.json
- src/test/resources/alma/(DE-605)HT017015300.json
- src/test/resources/alma/(DE-605)HT019246898.json
- src/test/resources/alma/(OCoLC)1073526105.json
> Change type in subject  to array (#1203)

- src/main/resources/alma/common/contribution.xml
- src/test/resources/alma/(DE-605)HT016709661.json
- src/test/resources/alma/(DE-605)HT019246898.json
- src/test/resources/alma/(DE-605)HT020391499.json
- src/test/resources/alma/(OCoLC)1073526105.json
> Add '[17]10[012] .b' to Contribution.agent.label

- src/main/resources/alma/common/item.xml
- src/test/resources/alma/(DE-605)HT000161712.json
- src/test/resources/alma/(DE-605)HT000312236.json
- src/test/resources/alma/(DE-605)HT005207972.json
- src/test/resources/alma/(DE-605)HT015671602.json
- src/test/resources/alma/(DE-605)HT017015300.json
- src/test/resources/alma/(DE-605)HT017398609.json
- src/test/resources/alma/(DE-605)HT019246898.json
> Add ITM  .n as possible subfield for callNumber (#1160)

- src/main/resources/alma/common/fields.xml
- src/test/resources/alma/(DE-605)TT050421649.json
> Rename "identifierDOI" to "doi" (#1238)

- src/main/resources/alma/common/fields.xml
- src/test/resources/alma/(DE-605)HT000161712.json
- src/test/resources/alma/(DE-605)HT012734833.json
- src/test/resources/alma/(DE-605)HT012734884.json
- src/test/resources/alma/(DE-605)HT015011399.json
- src/test/resources/alma/(DE-605)HT015671602.json
- src/test/resources/alma/(DE-605)HT016709661.json
- src/test/resources/alma/(DE-605)HT017015300.json
- src/test/resources/alma/(DE-605)HT017398609.json
- src/test/resources/alma/(DE-605)HT017411546.json
- src/test/resources/alma/(DE-605)HT017664407.json
- src/test/resources/alma/(DE-605)HT019246898.json
- src/test/resources/alma/(DE-605)HT020202475.json
- src/test/resources/alma/(DE-605)HT020391499.json
- src/test/resources/alma/(DE-605)TT050421649.json
Both transformations were not set up correctly.
See #1242
> Outcomment `hasVersion` and `related` (#1242)

- src/main/resources/alma/common/fields.xml
- src/test/resources/alma/(DE-605)HT017015300.json
- src/test/resources/alma/(DE-605)HT019246898.json
I rearranged the isPartOf mapping a little bit too, to prevent mixed objects.
> Add `830` as isPartOf (#1179)

- src/main/resources/alma/common/subjects.xml
- src/test/resources/alma/(DE-605)HT000312236.json
- src/test/resources/alma/(DE-605)HT003176544.json
- src/test/resources/alma/(DE-605)HT012734884.json
- src/test/resources/alma/(DE-605)HT017411546.json
> Deduplicate subjectAltLabel (#1232)

- src/main/resources/alma/common/subjects.xml
- src/test/resources/alma/(DE-605)HT000161712.json
- src/test/resources/alma/(DE-605)HT003176544.json
- src/test/resources/alma/(DE-605)HT006855611.json
- src/test/resources/alma/(DE-605)HT012734833.json
- src/test/resources/alma/(DE-605)HT012734884.json
- src/test/resources/alma/(DE-605)HT017411546.json
- src/test/resources/alma/(DE-605)HT019246898.json
> Add 655 as natureOfContent (#1219)

- src/main/resources/alma/common/fields.xml
- src/test/resources/alma/(DE-605)HT012734833.json
- src/test/resources/alma/(DE-605)HT012734884.json
- src/test/resources/alma/(DE-605)HT015011399.json
- src/test/resources/alma/(DE-605)HT017015300.json
- src/test/resources/alma/(DE-605)HT017411546.json
- src/test/resources/alma/(DE-605)HT017664407.json
- src/test/resources/alma/(DE-605)HT019246898.json
- src/test/resources/alma/(DE-605)HT020202475.json
- src/test/resources/alma/(DE-605)HT020391499.json
- src/test/resources/alma/(DE-605)TT050421649.json
Resolve part of #1242. Replaces #1256
> Remodel related-element + add ISBN, ISSN, note

- src/main/resources/alma/common/contribution.xml
- src/test/resources/alma/(DE-605)HT016709661.json
- src/test/resources/alma/(DE-605)HT017411546.json
- src/test/resources/alma/(DE-605)HT019246898.json
Also changed the workflow so that the gnd makro is used with organizations (110 /710) too
> Add gndIdentifier for Organizatio #1246

- src/main/resources/alma/common/subjects.xml
- src/test/resources/alma/(DE-605)HT000312236.json
- src/test/resources/alma/(DE-605)HT016709661.json
- src/test/resources/alma/(DE-605)HT017411546.json
@hagbeck asked for those specific format subjects unfortunately they do not have gndIdentifiers. Therefore we only have labels.
> Add format subject from 689 to natureOfContent (#1268)

- src/main/resources/alma/common/subjects.xml
- src/test/resources/alma/(DE-605)HT019246898.json
> Add 653 Index Term-Uncontrolled as subject type: keyword

- src/main/java/org/lobid/resources/EtikettJson.java
- src/main/java/org/lobid/resources/run/AlmaMarcXml2lobidJsonEs.java
- src/test/java/org/lobid/resources/AlmaMarc21XmlToLobidJsonTest.java
> 1281 fix labels loading

- src/main/java/org/lobid/resources/EtikettJson.java
- src/main/java/org/lobid/resources/run/AlmaMarcXml2lobidJsonEs.java
- src/test/java/org/lobid/resources/AlmaMarc21XmlToLobidJsonTest.java
> 1286 fix etikett json to output jsonl

- web/app/controllers/resources/Webhook.java
> Reload configs dynamically whenever route is invoked

- src/test/java/org/lobid/resources/AlmaMarc21XmlToLobidJsonTest.java
When using a pattern without any wildcard the filtering is really fast.
Also, when using a bgzf as test file this is recognized automatically.
- avoid "*.json0" as temporary test files
See #1222.
> Add bgzf in test; comment how to properly filter xml

- src/main/resources/alma/common/titleRelatedFields.xml
- src/test/resources/alma/(CKB)5280000000199164.json
- src/test/resources/alma/(DE-605)HT000161712.json
- src/test/resources/alma/(DE-605)HT000312236.json
- src/test/resources/alma/(DE-605)HT003176544.json
- src/test/resources/alma/(DE-605)HT004285445.json
- src/test/resources/alma/(DE-605)HT005207972.json
- src/test/resources/alma/(DE-605)HT006855611.json
- src/test/resources/alma/(DE-605)HT012734833.json
- src/test/resources/alma/(DE-605)HT012734884.json
- src/test/resources/alma/(DE-605)HT015011399.json
- src/test/resources/alma/(DE-605)HT015671602.json
- src/test/resources/alma/(DE-605)HT016709661.json
- src/test/resources/alma/(DE-605)HT017015300.json
- src/test/resources/alma/(DE-605)HT017398609.json
- src/test/resources/alma/(DE-605)HT017411546.json
- src/test/resources/alma/(DE-605)HT017664407.json
- src/test/resources/alma/(DE-605)HT019246898.json
- src/test/resources/alma/(DE-605)HT020202475.json
- src/test/resources/alma/(DE-605)HT020391499.json
- src/test/resources/alma/(DE-605)TT003907920.json
- src/test/resources/alma/(DE-605)TT050421649.json
> Add publication>startDate and endDate (#1279)

- src/main/java/org/lobid/resources/run/AlmaMarcXml2lobidJsonEs.java
- src/main/resources/alma/common/describedBy.xml
- src/test/java/org/lobid/resources/AlmaMarc21XmlToLobidJsonTest.java
- src/test/resources/alma/(CKB)5280000000199164.json
- src/test/resources/alma/(DE-605)HT000161712.json
- src/test/resources/alma/(DE-605)HT000312236.json
- src/test/resources/alma/(DE-605)HT003176544.json
- src/test/resources/alma/(DE-605)HT004285445.json
- src/test/resources/alma/(DE-605)HT005207972.json
- src/test/resources/alma/(DE-605)HT006855611.json
- src/test/resources/alma/(DE-605)HT012734833.json
- src/test/resources/alma/(DE-605)HT012734884.json
- src/test/resources/alma/(DE-605)HT015011399.json
- src/test/resources/alma/(DE-605)HT015671602.json
- src/test/resources/alma/(DE-605)HT016709661.json
- src/test/resources/alma/(DE-605)HT017015300.json
- src/test/resources/alma/(DE-605)HT017398609.json
- src/test/resources/alma/(DE-605)HT017411546.json
- src/test/resources/alma/(DE-605)HT017664407.json
- src/test/resources/alma/(DE-605)HT019246898.json
- src/test/resources/alma/(DE-605)HT020202475.json
- src/test/resources/alma/(DE-605)HT020391499.json
- src/test/resources/alma/(DE-605)TT003907920.json
- src/test/resources/alma/(DE-605)TT050421649.json
> Remove "resultOf.endTime" from test files

- src/main/resources/alma/common/subjects.xml
- src/test/resources/alma/(CKB)5280000000199164.json
> Deduplicate natureOfContent (#1271)

- src/main/resources/alma/alma.xml
- src/main/resources/alma/common/describedBy.xml
- src/main/resources/alma/common/fields.xml
- src/test/resources/alma/(CKB)5280000000199164.json
- src/test/resources/alma/(DE-605)HT000161712.json
- src/test/resources/alma/(DE-605)HT000312236.json
- src/test/resources/alma/(DE-605)HT003176544.json
- src/test/resources/alma/(DE-605)HT004285445.json
- src/test/resources/alma/(DE-605)HT005207972.json
- src/test/resources/alma/(DE-605)HT006855611.json
- src/test/resources/alma/(DE-605)HT012734833.json
- src/test/resources/alma/(DE-605)HT012734884.json
- src/test/resources/alma/(DE-605)HT015011399.json
- src/test/resources/alma/(DE-605)HT015671602.json
- src/test/resources/alma/(DE-605)HT016433929.json
- src/test/resources/alma/(DE-605)HT016709661.json
- src/test/resources/alma/(DE-605)HT017015300.json
- src/test/resources/alma/(DE-605)HT017398609.json
- src/test/resources/alma/(DE-605)HT017411546.json
- src/test/resources/alma/(DE-605)HT017664407.json
- src/test/resources/alma/(DE-605)HT019246898.json
- src/test/resources/alma/(DE-605)HT020202475.json
- src/test/resources/alma/(DE-605)HT020391499.json
- src/test/resources/alma/(DE-605)TT003907920.json
- src/test/resources/alma/(DE-605)TT050421649.json
Change all connected processes and delete id links that are not needed.
> Build id with almaMmsId (#1193)

- src/main/java/org/lobid/resources/run/AlmaMarcXml2lobidJsonEs.java
- src/main/java/org/lobid/resources/run/SwitchEsAlmaAlias.java
- src/main/resources/log4j2.xml
- web/app/Global.java
- web/app/controllers/resources/Webhook.java
- web/conf/log4j2.xml
- web/conf/logback.xml
- web/conf/resources.conf
> 1336 add mailto error

- src/main/java/de/hbz/lobid/helper/HttpPoster.java
- src/main/java/org/lobid/resources/run/AlmaMarcXml2lobidJsonEs.java
- web/app/Global.java
- web/app/controllers/resources/Webhook.java
- web/conf/resources.conf
> Add trigger webhook when ETL successful (#1380)

- src/main/resources/alma/alma.fix
- src/main/resources/alma/fix/fields.fix
- src/test/resources/alma-fix/(DE-605)HT000312236.json
- src/test/resources/alma-fix/(DE-605)HT004285445.json
- src/test/resources/alma-fix/(DE-605)HT014176012.json
- src/test/resources/alma-fix/(DE-605)HT016709661.json
- src/test/resources/alma-fix/(DE-605)HT017411546.json
- src/test/resources/alma-fix/(DE-605)HT017664407.json
- src/test/resources/alma-fix/(DE-605)HT018295975.json
- src/test/resources/alma-fix/(DE-605)HT018468645.json
- src/test/resources/alma-fix/(DE-605)HT018468645.xml
- src/test/resources/alma-fix/(DE-605)HT019631849.json
- src/test/resources/alma-fix/(DE-605)TT050421649.json
- src/test/resources/alma/(DE-605)HT018468645.json
- src/test/resources/alma/(DE-605)HT018468645.xml
Related to #1390 
Builds on #1384 and #1389
> 1390 links

- src/main/resources/alma/alma.fix
- src/main/resources/alma/fix/fields.fix
- src/test/resources/alma-fix/(DE-605)HT000312236.json
- src/test/resources/alma-fix/(DE-605)HT004285445.json
- src/test/resources/alma-fix/(DE-605)HT014176012.json
- src/test/resources/alma-fix/(DE-605)HT016709661.json
- src/test/resources/alma-fix/(DE-605)HT017411546.json
- src/test/resources/alma-fix/(DE-605)HT017664407.json
- src/test/resources/alma-fix/(DE-605)HT018295975.json
- src/test/resources/alma-fix/(DE-605)HT018468645.json
- src/test/resources/alma-fix/(DE-605)HT018468645.xml
- src/test/resources/alma-fix/(DE-605)HT019631849.json
- src/test/resources/alma-fix/(DE-605)TT050421649.json
- src/test/resources/alma/(DE-605)HT018468645.json
- src/test/resources/alma/(DE-605)HT018468645.xml
As #1392 but rebased on master.
> 1390 links 

- src/main/resources/alma/fix/subjects.fix
@dr0i so lets try this. This should solve: https://github.com/metafacture/metafacture-fix/issues/258#issuecomment-1248185006
I also deleted an alteration of subelements since that is not supported yet: https://github.com/metafacture/metafacture-fix/issues/249#issuecomment-1210945950
> Do once schlagwortfolgen macro

- src/main/java/org/lobid/resources/run/AlmaMarcXmlFix2lobidJsonEs.java
- src/main/resources/alma/fix/subjects.fix
- src/test/java/org/lobid/resources/AlmaMarc21XmlToLobidJsonMetafixTest.java
- src/test/resources/alma-fix/990171142550206441.json
- src/test/resources/alma-fix/990210667610206441.json
Enables lookup for deweyLabels. Variable for "deweyLabels" needs to be changed at the server. @dr0i knows what to do.
> Enable lookup for deweyLabels  #1425

- src/main/java/org/lobid/resources/run/AlmaMarcXml2lobidJsonEs.java
> 1430 timing webhook trigger

- src/main/resources/index-config.json
See https://jira.hbz-nrw.de/browse/RPB-27
> Add RPB-specific fields to index mapping config

- web/app/controllers/resources/Queries.java
See:
https://jira.hbz-nrw.de/browse/RPB-27 & https://github.com/hbz/lobid-resources/pull/1436
> Add RPB-specific fields to IdQuery (RPB-27)

- src/main/resources/alma/alma.fix
- src/main/resources/alma/fix/titleRelatedFields.fix
- src/test/resources/alma-fix/990033263300206441.json
- src/test/resources/alma-fix/990053976760206441.json
- src/test/resources/alma-fix/990108873860206441.json
- src/test/resources/alma-fix/990108874370206441.json
- src/test/resources/alma-fix/990173811970206441.json
- src/test/resources/alma-fix/990194668760206441.json
- src/test/resources/alma-fix/990197067610206441.json
Sidenote: HT017551955 and CT003043468 are those dublicates?
> Add element "titleKeyword"

- web/app/controllers/resources/Lobid.java
- web/app/views/details.scala.html
- web/app/views/query.scala.html
- web/conf/resources.conf
- web/public/stylesheets/resources.css
Will resolve #1342.
Use almaMmsId, not hbzId for query and details views.
Also tweak logging for remaining issues with Alma data (like item URIs).
> Update resources UI for Alma data

- src/main/resources/alma/alma.fix
- src/main/resources/alma/fix/relatedRessourcesAndLinks.fix
- src/test/resources/alma-fix/990053976760206441.json
- src/test/resources/alma-fix/990054215550206441.json
- src/test/resources/alma-fix/990054301770206441.json
- src/test/resources/alma-fix/990108874370206441.json
- src/test/resources/alma-fix/990184127410206441.json
- src/test/resources/alma-fix/991005935279706485.json
@acka47 hinted to this problem.
> Tweak typo in successor transformation #1475

- src/main/resources/index-config.json
> Switch almaIdMMS to almaMmsId in index-config.json (#1330)

- web/scripts/getLogsErrorsETL.sh
> Mail MapperParsingExceptions in ETL.log (#1512)

- src/main/java/org/lobid/resources/run/AlmaMarcXmlFix2lobidJsonEs.java
- src/main/resources/alma/fix/maps.fix
- src/test/java/org/lobid/resources/AlmaMarc21XmlToLobidJsonMetafixTest.java
Similar to f59c5d09ea28e20775910bcc1c5356d75fb8fda2.
See #1526.
> Fix resolving file "institutions.tsv" (#1526)

- src/main/resources/alma/fix/item.fix
- src/main/resources/labels/context-labels.json
- src/test/resources/alma-fix/990001412590206441.json
- src/test/resources/alma-fix/990011470300206441.json
- src/test/resources/alma-fix/990014830510206441.json
- src/test/resources/alma-fix/990016782920206441.json
- src/test/resources/alma-fix/990021367710206441.json
- src/test/resources/alma-fix/990021974470206441.json
- src/test/resources/alma-fix/990033263300206441.json
- src/test/resources/alma-fix/990035016180206441.json
- src/test/resources/alma-fix/990053976760206441.json
- src/test/resources/alma-fix/990063549080206441.json
- src/test/resources/alma-fix/990114098170206441.json
- src/test/resources/alma-fix/990118562160206441.json
- src/test/resources/alma-fix/990124590390206441.json
- src/test/resources/alma-fix/990126276700206441.json
- src/test/resources/alma-fix/990171142550206441.json
- src/test/resources/alma-fix/990181275760206441.json
- src/test/resources/alma-fix/990189160110206441.json
- src/test/resources/alma-fix/990193094010206441.json
- src/test/resources/alma-fix/990210237770206441.json
- src/test/resources/alma-fix/990210950050206441.json
- src/test/resources/alma-fix/990217478660206441.json
- src/test/resources/alma-fix/990223521400206441.json
- src/test/resources/alma-fix/991000688209706449.json
- src/test/resources/alma-fix/99370782520706441.json
> Introduce `serialNumber` for Buchungsnummer #1466

- src/main/resources/alma/fix/identifiers.fix
- src/test/resources/alma-fix/990363946050206441.json
- src/test/resources/alma-fix/990365842280206441.json
> Add missing `doi` from `856` #1439

- src/main/resources/alma/fix/contribution.fix
- src/test/resources/alma-fix/990156027740206441.json
- src/test/resources/alma-fix/990210781980206441.json
- src/test/resources/alma-fix/990367731740206441.json
#1307
@hagbeck and @UBmakla You asked for ORCIDs. Would this be okay for you?
> Add orcid as sameAs element #1307

- src/main/resources/alma/fix/titleRelatedFields.fix
- src/test/resources/alma-fix/990011470300206441.json
- src/test/resources/alma-fix/990021974470206441.json
- src/test/resources/alma-fix/990030574430206441.json
- src/test/resources/alma-fix/990051708340206441.json
- src/test/resources/alma-fix/990052965140206441.json
- src/test/resources/alma-fix/990053976760206441.json
- src/test/resources/alma-fix/990108740950206441.json
- src/test/resources/alma-fix/990108874370206441.json
- src/test/resources/alma-fix/990110509950206441.json
- src/test/resources/alma-fix/990193229450206441.json
- src/test/resources/alma-fix/990199611280206441.json
> Uniq publication.location #1233

- src/main/resources/alma/fix/relatedRessourcesAndLinks.fix
- src/test/resources/alma-fix/990183092590206441.json
- src/test/resources/alma-fix/990190567380206441.json
- src/test/resources/alma-fix/990210312460206441.json
- src/test/resources/alma-fix/990226763120206441.json
> 1410 contained in label

- src/main/resources/alma/fix/mediumAndType.fix
- src/test/resources/alma-fix/990110509950206441.json
- src/test/resources/alma-fix/990110714900206441.json
- src/test/resources/alma-fix/990110881770206441.json
- src/test/resources/alma-fix/990114617880206441.json
- src/test/resources/alma-fix/990123613330206441.json
- src/test/resources/alma-fix/990183092590206441.json
- src/test/resources/alma-fix/990190567380206441.json
- src/test/resources/alma-fix/990210312460206441.json
- src/test/resources/alma-fix/990226763120206441.json
> Add transformation for Articles in ALMA #1455

- src/main/resources/alma/fix/contribution.fix
- src/main/resources/alma/fix/relatedRessourcesAndLinks.fix
- src/main/resources/alma/fix/titleRelatedFields.fix
- src/test/resources/alma-fix/990035016180206441.json
- src/test/resources/alma-fix/990051552280206441.json
- src/test/resources/alma-fix/990063549080206441.json
- src/test/resources/alma-fix/990141342350206441.json
- src/test/resources/alma-fix/990183092590206441.json
- src/test/resources/alma-fix/990185607520206441.json
- src/test/resources/alma-fix/990194744870206441.json
- src/test/resources/alma-fix/990196925330206441.json
- src/test/resources/alma-fix/990210285400206441.json
- src/test/resources/alma-fix/990213906490206441.json
- src/test/resources/alma-fix/990226763120206441.json
> 1543 not sorting signs

- src/main/resources/alma/fix/mediumAndType.fix
- src/test/resources/alma-fix/990050000600206441.json
- src/test/resources/alma-fix/990051552280206441.json
- src/test/resources/alma-fix/990051708340206441.json
- src/test/resources/alma-fix/990173811970206441.json
> Add type MultiVolumeBook #1456

- src/main/resources/alma/alma.fix
- src/main/resources/alma/fix/mediumAndType.fix
- src/main/resources/alma/fix/otherFields.fix
- src/main/resources/alma/fix/relatedRessourcesAndLinks.fix
- src/main/resources/alma/fix/titleRelatedFields.fix
- src/test/resources/alma-fix/990054301770206441.json
- src/test/resources/alma-fix/990103899140206441.json
- src/test/resources/alma-fix/990110509950206441.json
- src/test/resources/alma-fix/990114617880206441.json
- src/test/resources/alma-fix/990118562160206441.json
- src/test/resources/alma-fix/990123613330206441.json
- src/test/resources/alma-fix/990150856900206441.json
- src/test/resources/alma-fix/990181275760206441.json
- src/test/resources/alma-fix/990207856340206441.json
- src/test/resources/alma-fix/990210781980206441.json
- src/test/resources/alma-fix/990225056670206441.json
- src/test/resources/alma-fix/991000688209706449.json
- src/test/resources/alma-fix/99370782520706441.json
- delete comments
- exclude reviews from abstracts
- delete titleOfSubseries
- create isPartOf if 773 is a subvolume
> Several smaller changes

- src/main/resources/alma/fix/titleRelatedFields.fix
- src/test/resources/alma-fix/990220027540206441.json
- src/test/resources/alma-fix/990220027540206441.xml
> 1560-indianYears

- web/app/controllers/resources/Application.java
- web/app/controllers/resources/Lobid.java
- web/app/views/TableRow.java
Will resolve #1592.
Also using relative links to stay in the Alma-based `test.lobid.org` system.
> Try ID search and using actual ID if label lookup fails

- src/main/resources/alma/fix/titleRelatedFields.fix
- src/test/resources/alma-fix/990118562160206441.json
> Keep trailing dot if ... at end of title #1591

- src/main/resources/alma/fix/mediumAndType.fix
- src/test/resources/alma-fix/990103899140206441.json
- src/test/resources/alma-fix/990136041660206441.json
- src/test/resources/alma-fix/990136041660206441.xml
I added the example since it is a specific RPB example and differs from the existing example that it has only one subfield $n.
Related #1626
> 1626 wrong type publication issue

- src/main/resources/alma/fix/mediumAndType.fix
- web/conf/resources.conf_template
I follow @acka47 instructions from #1447
> Change Tonband in GUI to Kassette #1447

- web/app/views/tags/result_doc.scala.html
> Add alternativeTitle field to details view

- src/main/resources/index-config.json
Required for DigiBib integration (https://jira.hbz-nrw.de/browse/DOX-1588).
Resolves (part of) #1617.
> Add aggregations support for language and medium labels.

- src/main/resources/alma/fix/relatedRessourcesAndLinks.fix
- src/test/resources/alma-fix/99371123630706441.json
- src/test/resources/alma-fix/99371123630706441.xml
> 1625-joinHasSuperorrdinateLabels

- src/main/resources/alma/fix/relatedRessourcesAndLinks.fix
- src/test/resources/alma-fix/990063549080206441.json
- src/test/resources/alma-fix/990075429930206441.json
- src/test/resources/alma-fix/990075429930206441.xml
- src/test/resources/alma-fix/990114617880206441.json
Fixing monitored error 
```
990075429930206441
2023-03-11 23:57:46 +0100 [WARN] from org.metafacture.metafix.Metafix in Thread-16 - Error while executing Fix expression (at file:/home/sol/git/lobid-resources-alma/web/target/universal/stage/conf/alma/fix/relatedRessourcesAndLinks.fix, line 204): replace_all("isPartOf[].*.hasSuperordinate[].*.id", "^\\(DE-605\\)(.*)$", "http://lobid.org/resources/$1#!")
```
> FixFixError

- src/main/resources/index-config.json
Required for DigiBib integration (https://jira.hbz-nrw.de/browse/DOX-1588).
Resolves (part of) #1614.
> Add unstemmed contribution label and altLabel.

- src/main/resources/alma/fix/mediumAndType.fix
- src/test/resources/alma-fix/990058434730206441.json
- src/test/resources/alma-fix/990065341720206441.json
> Only map main extend info #1567

- src/main/resources/alma/fix/subjects.fix
- src/test/resources/alma-fix/990075538650206441.json
- src/test/resources/alma-fix/990075538650206441.xml
Add Medical Subject Headings (MeSH) if they are listed with indicator 2=7
> 1672-meshInd7

- src/main/resources/alma/fix/titleRelatedFields.fix
- src/test/resources/alma-fix/990035016180206441.json
- src/test/resources/alma-fix/990104908070206441.json
- src/test/resources/alma-fix/990118562160206441.json
- src/test/resources/alma-fix/990193229450206441.json
- src/test/resources/alma-fix/990196925330206441.json
- src/test/resources/alma-fix/990197023370206441.json
- src/test/resources/alma-fix/990197067610206441.json
Now it also catches endDates if there is a space between the year and the -
> 1485-secondaryPublication

- src/main/resources/alma/fix/maps.fix
- src/main/resources/alma/maps/institutions.tsv
See #1650
I used @blackwinter s list to create this list.
> Update library list #1650

- src/main/resources/alma/fix/mediumAndType.fix
- src/test/resources/alma-fix/990015048200206447.json
- src/test/resources/alma-fix/990112067120206441.json
- src/test/resources/alma-fix/990156027740206441.json
- src/test/resources/alma-fix/990185619180206441.json
- src/test/resources/alma-fix/990197067610206441.json
- src/test/resources/alma-fix/990197293880206441.json
- src/test/resources/alma-fix/990206060640206441.json
- src/test/resources/alma-fix/990209817770206441.json
- src/test/resources/alma-fix/990217495840206441.json
- src/test/resources/alma-fix/990365842280206441.json
> Improve type Book mapping #1669

- src/main/resources/index-config.json
> Make subject `altLabel`s searchable.

- src/test/resources/alma-fix/updateAlmaTestFiles.sh
> Switch to use non-VPN URL to get test data

- src/main/resources/alma/fix/mediumAndType.fix
- src/test/resources/alma-fix/990122511970206441.json
- src/test/resources/alma-fix/990124590390206441.json
- src/test/resources/alma-fix/990183092590206441.json
- src/test/resources/alma-fix/990210285400206441.json
- web/conf/context.jsonld
> Introduce "MusicalRecording" #1685

- pom.xml
- src/main/resources/alma/index-config.json
- web/app/controllers/resources/LocalIndex.java
- web/app/views/rss.scala.html
- web/test/tests/IndexIntegrationTest.java
- web/test/tests/almafix/AcceptIntegrationTest.java
- web/test/tests/almafix/AcceptUnitTest.java
- web/test/tests/almafix/AggregationsTest.java
- web/test/tests/almafix/ApplicationTest.java
- web/test/tests/almafix/IndexIntegrationTest.java
- web/test/tests/almafix/InputStringsTest.java
- web/test/tests/almafix/IntegrationTests.java
- web/test/tests/almafix/LocalIndexSetup.java
- web/test/tests/almafix/NestedQueryTests.java
- web/test/tests/almafix/RdfConverterTests.java
- web/test/tests/almafix/ResponseStatusTests.java
> Add testing of  alma API

- web/app/controllers/resources/Lobid.java
> Handle non-ISILs when sorting by item IDs

- web/app/views/api.scala.html
Will resolve #1698.
(I've switched from [HT018472857](http://lobid.org/resources/HT018472857) to [990150876610206441](https://test.lobid.org/resources/990150876610206441) to have an example with items.)
> Update resource IDs in API doc for Alma data

- src/main/resources/alma/index-config.json
- web/test/tests/IndexIntegrationTest.java
> Fix index configuration for "describedBy.resultOf"

- src/main/resources/alma/alma.fix
- src/main/resources/alma/fix/relatedRessourcesAndLinks.fix
- src/main/resources/labels/context-labels.json
- src/test/resources/alma-fix/990114617880206441.json
- src/test/resources/alma-fix/990193806600206441.json
- src/test/resources/alma-fix/990194668760206441.json
This illustrates my suggestion from #1577
For links to Reproductions use property `hasFormat`
> Introduce hasFormat/secondaryForm for links to reproductions #1577

- src/main/resources/alma/fix/subjects.fix
- src/test/resources/alma-fix/990016782920206441.json
- src/test/resources/alma-fix/990207668220206441.json
- src/test/resources/alma-fix/990217495840206441.json
- src/test/resources/alma-fix/99371014448006441.json
> Add 688 as freie Verschlagwortung subject #1758

- .github/workflows/build.yml
Using sbt is also the way we build on our servers.
> Switch github actions from using activator to sbt

- src/main/resources/beacon/data/beacon_head.txt
- src/main/resources/beacon/makePndBeacon.sh
Adjust json path to the data .
Fix the date pattern.
Fix the beacon header.
Resolves #1710.
> Create beacon with Alma data

- web/app/controllers/resources/WebhookAlmaFix.java
See #1771.
Complements https://github.com/hbz/lobid-resources/pull/1773.
> Get real IP

- src/main/resources/alma/alma.fix
- src/main/resources/alma/fix/relatedRessourcesAndLinks.fix
- src/test/resources/alma-fix/990110509950206441.json
- src/test/resources/alma-fix/990118562160206441.json
- src/test/resources/alma-fix/990123613330206441.json
- src/test/resources/alma-fix/990150856900206441.json
- src/test/resources/alma-fix/990181275760206441.json
- src/test/resources/alma-fix/990207856340206441.json
- src/test/resources/alma-fix/990210781980206441.json
- src/test/resources/alma-fix/990220027540206441.json
- src/test/resources/alma-fix/990225056670206441.json
- src/test/resources/alma-fix/991000688209706449.json
- src/test/resources/alma-fix/99370782520706441.json
> Use "main" title (MARC `245$$a`) as fallback for `isPartOf.hasSuperordinate.label`.

- src/main/resources/alma/fix/titleRelatedFields.fix
- src/test/resources/alma-fix/990001412590206441.json
- src/test/resources/alma-fix/990035016180206441.json
- src/test/resources/alma-fix/990051708340206441.json
- src/test/resources/alma-fix/990054215550206441.json
- src/test/resources/alma-fix/990059571560206441.json
- src/test/resources/alma-fix/990063549080206441.json
- src/test/resources/alma-fix/990075538650206441.json
- src/test/resources/alma-fix/990110509950206441.json
- src/test/resources/alma-fix/990114098170206441.json
- src/test/resources/alma-fix/990123613330206441.json
- src/test/resources/alma-fix/990143325070206441.json
- src/test/resources/alma-fix/990172512030206441.json
- src/test/resources/alma-fix/990189160110206441.json
- src/test/resources/alma-fix/990193094010206441.json
- src/test/resources/alma-fix/990204246530206441.json
- src/test/resources/alma-fix/990206060640206441.json
> Keep  closing "]" in publication.location for u.a. #1735

- src/main/resources/alma/index-config.json
- web/test/tests/IndexIntegrationTest.java
Required for DigiBib integration (https://jira.hbz-nrw.de/browse/DOX-1588).
Resolves #1574 (alternative solution).
> Add aggregations support for bibliographicLevel labels.

- src/main/resources/labels/context-labels.json
Results from https://github.com/hbz/lobid-resources/issues/1574#issuecomment-1592544558.
> Add bibliographicLevel and ISIL to context

- web/app/controllers/resources/Application.java
- web/app/controllers/resources/Queries.java
- web/app/views/details.scala.html
- web/app/views/query.scala.html
- web/app/views/rss.scala.html
- web/app/views/stars.scala.html
- web/app/views/tags/result_doc.scala.html
Will resolve #1809.
Deployed to stage:
http://stage.lobid.org/resources/search?q=NOT+_exists_:(hbzId+OR+almaMmsId+OR+zdbId)
> UI support for RPB-only resources

- .github/workflows/build.yml
- pom.xml
- src/main/java/de/hbz/lobid/helper/CompareJsonMaps.java
- src/main/java/de/hbz/lobid/helper/Etikett.java
- src/main/java/de/hbz/lobid/helper/EtikettMaker.java
- src/main/java/de/hbz/lobid/helper/HttpPoster.java
- src/main/java/org/lobid/resources/ElasticsearchIndexer.java
- src/main/java/org/lobid/resources/EtikettJson.java
- src/main/java/org/lobid/resources/JsonLdEtikett.java
- src/main/java/org/lobid/resources/run/AlmaMarcXmlFix2lobidJsonEs.java
- src/main/java/org/lobid/resources/run/SwitchEsAlmaAlias.java
- src/main/java/org/lobid/resources/run/UpdateAliases.java
- src/test/java/org/lobid/resources/AlmaMarc21XmlToLobidJsonMetafixTest.java
This simplifies dependencies.
- update metafix dependency to 0.5.1
Originates from #1811.
> Switch to slf4j logger

- src/main/resources/alma/fix/relatedRessourcesAndLinks.fix
- src/test/resources/alma-fix/990001412590206441.json
- src/test/resources/alma-fix/990035016180206441.json
- src/test/resources/alma-fix/990054345550206441.json
- src/test/resources/alma-fix/990136041660206441.json
- src/test/resources/alma-fix/990173811970206441.json
- src/test/resources/alma-fix/990204246530206441.json
- src/test/resources/alma-fix/990204253490206441.json
- src/test/resources/alma-fix/990206060640206441.json
- src/test/resources/alma-fix/990210667610206441.json
- src/test/resources/alma-fix/990217495840206441.json
- src/test/resources/alma-fix/991005935279706485.json
- src/test/resources/alma-fix/99372423490706441.json
The mapping was wrong. Fixed it.
> Fix inCollection for RPB #1814

- src/main/resources/alma/alma.fix
- src/main/resources/alma/fix/otherFields.fix
- src/main/resources/labels/context-labels.json
- src/test/resources/alma-fix/990001412590206441.json
- src/test/resources/alma-fix/990033263300206441.json
- src/test/resources/alma-fix/990054215550206441.json
- src/test/resources/alma-fix/990183092590206441.json
- src/test/resources/alma-fix/990213906490206441.json
- src/test/resources/alma-fix/990226465800206441.json
- src/test/resources/alma-fix/990366394400206441.json
- src/test/resources/alma-fix/990368743120206441.json
- src/test/resources/alma-fix/99370746459806441.json
- src/test/resources/alma-fix/99370763882706441.json
- src/test/resources/alma-fix/99371123630706441.json
- src/test/resources/alma-fix/99371791018506441.json
- src/test/resources/alma-fix/99372423490706441.json
- web/conf/context.jsonld
Introduced a mapping for language note from Marc, see #1671
Also added the new property `langNote`. I have to introduce this to the vocab too.
> Add langNote mapping #1671

- web/conf/dataset.jsonld
> Fix contact link (#1821)

- src/main/resources/alma/fix/mediumAndType.fix
- src/test/resources/alma-fix/990210093550206441.json
- src/test/resources/alma-fix/99370690532406441.json
- src/test/resources/alma-fix/99370690532406441.xml
- src/test/resources/alma-fix/99371147104906441.json
- src/test/resources/alma-fix/99371147104906441.xml
@hagbeck : Have a look here.
The mapping with concern to the `"POR"` Element seems to create some confusion. Any suggestion how to proceed here? It seems that the same record can have `POR $$f` BOOK and JOURNAL.
https://github.com/hbz/lobid-resources/blob/7ba4a070546d5775330925cb88d56c0814ce5c88/src/test/resources/alma-fix/990210093550206441.xml#L245-L246
https://github.com/hbz/lobid-resources/blob/7ba4a070546d5775330925cb88d56c0814ce5c88/src/test/resources/alma-fix/990210093550206441.xml#L226-L227
> 1824 missing cz journals

- src/main/resources/alma/fix/relatedRessourcesAndLinks.fix
- src/test/resources/alma-fix/990001412590206441.json
- src/test/resources/alma-fix/990035016180206441.json
- src/test/resources/alma-fix/990054345550206441.json
- src/test/resources/alma-fix/990136041660206441.json
- src/test/resources/alma-fix/990173811970206441.json
- src/test/resources/alma-fix/990204246530206441.json
- src/test/resources/alma-fix/990206060640206441.json
- src/test/resources/alma-fix/991005935279706485.json
- src/test/resources/alma-fix/99372423490706441.json
> Exclude LBZ Notation as marker for inCollection=RPB #1856

- web/monit_restart.sh
> Set java option to prefer ipv4 

- web/app/controllers/resources/Search.java
- web/test/tests/AcceptIntegrationTest.java
- web/test/tests/IndexIntegrationTest.java
> Improve identification of failing queries

- web/conf/context.jsonld
I forgot to check in the context in the last time. We need to add the context and its changes now too. As suggested in  #1858
> Check inupdated context

- src/main/resources/alma/index-config.json
- web/test/tests/IndexIntegrationTest.java
> Add serialNumber to the index to be queryable

- README.textile
- src/main/resources/alma/index-config.json
- web/test/tests/IndexIntegrationTest.java
> Add index fields for DigiBib.

- .github/workflows/build.yml
- pom.xml
- src/test/resources/alma-fix/990367761810206441.json
I will open a ticket and have a look at the change in extend. Seems to be due to a repeated element.
> Update fix version

- src/main/resources/alma/fix/macros.fix
- src/test/resources/alma-fix/99372680948006441.json
- src/test/resources/alma-fix/99372680948006441.xml
Reported in logs
The examples seem non sensical  since they provide latin  alternativeGraphicRepresentation for a latin script record / ublicaation.
But they are an example for the fixed error.
> LogErrorInAlternativeGraphicRepresentation

- src/main/resources/alma/index-config.json
- src/main/resources/labels/context-labels.json
- web/app/views/TableRow.java
- web/conf/context.jsonld
> Delete unnecessary coverage related mappings/code #1884

- web/app/controllers/resources/Lobid.java
- web/app/views/tags/items_map.scala.html
> Use own json to get opac links

- .gitmodules
> Remove gitsubmodule "link-templates"

- .github/workflows/build.yml
- pom.xml
Uses https://github.com/metafacture/metafacture-fix/pull/327.
See #1666.
> Use metafix master SNAPSHOT

- web/app/views/TableRow.java
One of several results of  #1846:
There is no more "@graph" and also no "subjectChain". Also every "id" has a "label".
> Remove logic to get labels from keys

- web/app/views/dataset.scala.html
- web/conf/dataset.jsonld
> Remove link to dataset

- src/main/resources/alma/fix/relatedRessourcesAndLinks.fix
- src/test/resources/alma-fix/990367593690206441.json
- src/test/resources/alma-fix/990367593690206441.xml
- web/test/tests/IndexIntegrationTest.java
Use 1st occurrence of subfield w
Adjust regex for linking to related resources
> Fix related resource with repeated subfield

- README.textile
- src/main/resources/alma/fix/item.fix
- src/test/resources/alma-fix/990170546170206441.json
- src/test/resources/alma-fix/990170546170206441.xml
- web/test/tests/IndexIntegrationTest.java
> Adjust holdings for repeated subfield b (#1956)

- src/main/resources/alma/fix/identifiers.fix
- src/test/resources/alma-fix/990055981810206441.json
- src/test/resources/alma-fix/990170546170206441.json
- src/test/resources/alma-fix/991005935279706485.json
> Set ISSN-array to uniq (#1949)

- src/main/resources/alma/fix/titleRelatedFields.fix
- src/test/resources/alma-fix/991002103529706485.json
- src/test/resources/alma-fix/99370678063606441.json
- src/test/resources/alma-fix/99370690532406441.json
- src/test/resources/alma-fix/99370738710506441.json
- src/test/resources/alma-fix/99370746459806441.json
- src/test/resources/alma-fix/99370763433806441.json
- src/test/resources/alma-fix/99371107766906441.json
- src/test/resources/alma-fix/99371123630706441.json
- src/test/resources/alma-fix/99371147104906441.json
- src/test/resources/alma-fix/99371447897606441.json
- src/test/resources/alma-fix/99371449208306441.json
- src/test/resources/alma-fix/99372680948006441.json
> Remove superfluous characters from publ-location (#1953)

- src/main/resources/alma/fix/otherFields.fix
- src/test/resources/alma-fix/99371964653806441.json
- src/test/resources/alma-fix/99371964653806441.xml
- web/test/tests/IndexIntegrationTest.java
Examples: See [query](https://lobid.org/resources/search?q=language.label.raw%3A%22+++%22).
See also #1788.
> Exclude empty language codes.

- src/main/resources/alma/fix/titleRelatedFields.fix
- src/test/resources/alma-fix/990119186660206441.json
- src/test/resources/alma-fix/990119186660206441.xml
- web/test/tests/IndexIntegrationTest.java
> Adjust publication startDate for serials (#1799)

- .github/workflows/build.yml
- web/build.sbt
- web/monit_restart.sh
- web/project/build.properties
> Update Play app and GitHub action to Java 11 (#1965)

- src/main/resources/alma/fix/relatedRessourcesAndLinks.fix
- src/test/resources/alma-fix/99370970534006441.json
> Ignore 856 without subfield u for fulltextOnline (#1883)

- src/main/resources/alma/alma.fix
- src/main/resources/alma/fix/identifiers.fix
- src/test/resources/alma-fix/991005935279706485.json
- src/test/resources/alma-fix/99370678063606441.json
- src/test/resources/alma-fix/99370682219806441.json
- src/test/resources/alma-fix/99370694196806441.json
- src/test/resources/alma-fix/99370699582506441.json
> Only map HT Nr. for hbz NZ resources #1996

- CONTRIBUTING.md
> Initial landing of CONTRIBUTING.md

- src/main/resources/alma/fix/macros.fix
- src/test/resources/alma-fix/990123613330206441.json
- src/test/resources/alma-fix/990182814750206441.json
- src/test/resources/alma-fix/990365842280206441.json
- src/test/resources/alma-fix/991002103529706485.json
- src/test/resources/alma-fix/991005935279706485.json
- src/test/resources/alma-fix/99370690532406441.json
- src/test/resources/alma-fix/99370763433806441.json
- src/test/resources/alma-fix/99370763882706441.json
- src/test/resources/alma-fix/99371123630706441.json
- src/test/resources/alma-fix/99371314897806441.json
- src/test/resources/alma-fix/99371426239306441.json
- src/test/resources/alma-fix/99371447897606441.json
- src/test/resources/alma-fix/99371449208306441.json
- src/test/resources/alma-fix/99371463467006441.json
- src/test/resources/alma-fix/99371791018506441.json
- src/test/resources/alma-fix/99371964653806441.json
- src/test/resources/alma-fix/99372680948006441.json
> Map ebrary and E Book Central #1438

- src/main/resources/alma/fix/mediumAndType.fix
- src/test/resources/alma-fix/990054089950206441.json
- src/test/resources/alma-fix/990104908070206441.json
- src/test/resources/alma-fix/990118562160206441.json
- src/test/resources/alma-fix/990123613330206441.json
- src/test/resources/alma-fix/990185619180206441.json
- src/test/resources/alma-fix/990196925330206441.json
See #2009
There are two Audio Publications that have Print, but this is due to bad cataloguing. I reported this to Verbundgruppe.
> Map 007t to medium Print if not manuscript #2009

- src/main/resources/alma/fix/otherFields.fix
- src/test/resources/alma-fix/990054089950206441.json
> Do not map 501 to `bibliographicCitation` #2012

- src/main/resources/alma/fix/titleRelatedFields.fix
- src/test/resources/alma-fix/990054089950206441.json
Used to be part of the old ALEPH transformation. See #2014
> Add Coden to shortTitle #2014

- src/main/resources/alma/fix/otherFields.fix
- src/test/resources/alma-fix/990219911120206441.json
> Add RDA conforming thesisInformation #2018

- src/main/resources/alma/fix/subjects.fix
- src/test/resources/alma-fix/990026405480206441.json
- src/test/resources/alma-fix/990054089950206441.json
- src/test/resources/alma-fix/990054345550206441.json
- src/test/resources/alma-fix/990055981810206441.json
- src/test/resources/alma-fix/990063549080206441.json
- src/test/resources/alma-fix/990170546170206441.json
- src/test/resources/alma-fix/990173811970206441.json
- src/test/resources/alma-fix/990183054020206441.json
- src/test/resources/alma-fix/990183958380206441.json
- src/test/resources/alma-fix/990184127410206441.json
- src/test/resources/alma-fix/990193229450206441.json
- src/test/resources/alma-fix/990204246530206441.json
- src/test/resources/alma-fix/990226763120206441.json
- src/test/resources/alma-fix/990367731740206441.json
- src/test/resources/alma-fix/99370682219806441.json
- src/test/resources/alma-fix/99373637266706441.json
> Add fallback type for RSWK-subject without type #2030

- src/test/resources/schemas/spatial.json
Adjust spatial schema to validate RPB spatial info too. 
Related to #1340
> Schema: Adjust spatial schema to validate RPB spatial info too.

- src/main/resources/alma/fix/mediumAndType.fix
- src/test/resources/alma-fix/990054089950206441.json
- src/test/resources/alma-fix/990103770440206441.json
- src/test/resources/alma-fix/990108740950206441.json
- src/test/resources/alma-fix/990136041660206441.json
- src/test/resources/alma-fix/990196925330206441.json
- src/test/resources/alma-fix/990197023370206441.json
> Tag type:newspaper as type:periodical too #1991

- .github/workflows/build.yml
> Add action for testing the output with json-schema #2051

- src/main/resources/alma/fix/macros.fix
- src/test/resources/alma-fix/990172512030206441.json
> Add $f for GND subject work #2058

- scripts/generateRvkConcordance.sh
- src/main/java/org/lobid/resources/run/CulturegraphXmlFilterHbzRvkToTsv.java
> Update monthly rvk from culturegraph

- pom.xml
> Exclude metafix' log4j12 dependency to fix logging

- web/conf/context.jsonld
After running `mvn clean install -DskipTests=false -DgenerateTestData=true` Database was added. This seems to be a good reason to update the `context.jsonld`-file
> Update `context.jsonld` automatically #1864

- src/main/resources/alma/maps/institutions.tsv
- Change member names according to Alma. (Wave 1-3)
- Add new members after Cutover. (Wave 24)
> Update Alma institutions.

- src/main/resources/alma/fix/item.fix
- src/main/resources/alma/fix/macros.fix
See hbz/lookup-tables#60. Also see #2098
> Include current library when looking up Alma suppressed location.

- .github/workflows/build.yml
> Update to actions/cache@v4

- src/main/resources/alma/fix/describedBy.fix
- src/main/resources/alma/fix/macros.fix
- src/main/resources/alma/fix/titleRelatedFields.fix
- src/test/resources/alma-fix/99371910920106441.json
- src/test/resources/alma-fix/99371910920106441.xml
- web/test/tests/IndexIntegrationTest.java
Adjust date checker. See #2167
This should prevent the recent MapperParsingException
> 2167-brokenDate

- src/main/resources/alma/index-config.json
- web/app/controllers/resources/Queries.java
Requirement from https://jira.hbz-nrw.de/browse/RPB-288
> Add `hebisId` to `IdQuery` and index-config.json

- web/app/controllers/resources/Search.java
- web/test/tests/IntegrationTests.java
> Retain field order in JSON search responses

- src/main/resources/labels/context-labels.json
See #2196 
Related to https://github.com/hbz/lobid-vocabs/pull/237
> Add missing context properties #2196
