install-dependencies.sh
pom.xml

- add jitpack repository to pom
- add lobid-rdf-to-json dependency to pom
- remove git building lobid-rdf-to-json from script
Resolves hbz/lobid-rdf-to-json#32.

Use jitpack to handle lobid-rdf-to-json library

---

src/main/resources/morph-hbz01-to-lobid.xml
src/test/resources/hbz01.es.nt
src/test/resources/jsonld/HT004381366

Fixes #44. The atom editor obvioulsy made some automatic adjustments. I guess they don't hurt. The relevant change happened in [line 1669](https://github.com/hbz/lobid-resources/compare/44-add700nbToCoverage?expand=1#diff-9cd7dc3a9e57c8e575367094c6f3306bL1669).
(I also forgot to refer to the issue in the commit. Will try to remember it next time.)

Add 700n.b for other spatial notations to "coverage".

---

src/test/resources/buildAndETLTestSet.sh

This way the "small test index" can't get into the way of the productive index.

Change index name for small test

---

pom.xml
src/test/resources/hbz01.es.nt
src/test/resources/jsonld/BT000110055
src/test/resources/jsonld/CT003012479
src/test/resources/jsonld/HT009993506
src/test/resources/jsonld/HT015894164
src/test/resources/jsonld/HT017411546
src/test/resources/jsonld/HT018290299
src/test/resources/jsonld/HT018617137
src/test/resources/jsonld/HT018700720
src/test/resources/jsonld/TT002234042
src/test/resources/jsonld/TT002234459
src/test/resources/jsonld/TT050409948

Helps to resolve hbz/lobid-rdf-to-json#74.
Makes also bnode agents single entries.
Same for secondaryPublication.

Update lobid-rdf-to-json dependency

---

src/main/resources/morph-hbz01-to-lobid.xml
src/test/resources/jsonld/HT018290299

Resolves #172.
Some resources are part of multiple series and in such a case
the "numbering" could have multiple entries, expected were just one.
The morph "reset" fixes this.

Fix double numbering entry

---

web/app/controllers/resources/Application.java
web/app/controllers/resources/Index.java
web/app/views/tags/issued_facet.scala.html
web/test/tests/ExternalIntegrationTest.java
web/test/tests/IndexUnitTest.java
web/test/tests/TravisTests.java

Will resolve https://github.com/hbz/lobid-resources-web/issues/35
Support via `*`, see: [http://test.lobid.org/resources/search?issued=2010-*](http://test.lobid.org/resources/search?issued=2010-*)
While adding this, I've cleaned up the code and added general tests for building the query, so this is a good changeset and should be merged in principle. However, considering documentation for this brings up an issue we did not discuss yet: since the web UI evolved from NWBib, it still uses the NWBib query parameters (like `issued` here). These are internally mapped to the queryString syntax. For this example:
http://test.lobid.org/resources/search?q=*%20AND%20(%20+publication.startDate:[2010%20TO%20*])
So we would not need many of the parameters, however the queryString is quite verbose as an …

Support wildcards in issued range queries

---

src/main/resources/context.json
src/main/resources/labels/labels.json

Resolves #234
Also removes the input and output folders of HT013480902 and HT019093814 as they are removed from the hbz01XmlClobs.tar.gz.

Replace bibo with bibframe Collection

---

web/app/controllers/resources/Application.java
web/app/controllers/resources/Index.java
web/conf/resources.routes
web/test/tests/AggregationsTest.java
web/test/tests/AllQuickTests.java
web/test/tests/InputStringsTest.java

See https://github.com/hbz/lobid-resources-web/issues/26
Deployed to staging:
http://test.lobid.org/resources/search?q=glessen&format=json (no aggregations)
http://test.lobid.org/resources/search?q=glessen&format=json&aggregations=subject.id,owner (supported)
http://test.lobid.org/resources/search?q=glessen&format=json&aggregations=title (unsupported)

Support customizable aggregations, none as default

---

src/main/java/org/lobid/resources/run/DownloadTestSet.java

Set URL of hbz01 MabXmlClobs source to productive one
The "test" subdomain gives http status code 404.

Update URL for hbz01 MabXmlClobs used by download test-set

---

.travis.yml

Will resolve https://github.com/hbz/lobid-resources/issues/273
See build details: https://travis-ci.org/hbz/lobid-resources/builds/206095808
Configured as documented in:
https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
Add a separate compilation step with increased timeout to avoid higher timeout when actually running tests (where timing out would indicate a problem).

Increase timeout for Travis

---

web/conf/dataset.jsonld

Same as https://github.com/hbz/lobid-organisations/pull/343#issue-217256236:
> Just a small change. We should use `dcat:distribution` rather than `schema:distribution` because
>
> 1. it is recommended by https://www.w3.org/TR/dwbp/#metadata
> 2. it better fits our use case as `schema:distribution` let's you rather expect a downloadable data dump (from the description: "A downloadable form of this dataset, at a specific location, in a specific format.")

Adjust dataset description to follow W3C recommendation

---

web/app/controllers/resources/Accept.java
web/app/controllers/resources/Application.java
web/app/controllers/resources/Index.java
web/test/tests/IntegrationTests.java

Will resolve https://github.com/hbz/lobid-resources/issues/330.
Sample usage (increasing response size):
`curl "http://localhost:9000/resources/search?q=ehrenfeld&format=bulk" > ehrenfeld.jsonl`
`curl "http://localhost:9000/resources/search?q=dom&format=bulk" > dom.jsonl`
`curl "http://localhost:9000/resources/search?q=*&format=bulk" > resources.jsonl`
Response format for `format=bulk` is JSON lines (see http://jsonlines.org/).
Updates since a specific date can be requested as part of the query (was `scroll=20100101` in 1.x):
`curl "http://localhost:9000/resources/search?q=ehrenfeld+AND+describedBy.dateModified:>20100101&format=bulk" > ehrenfeld-since-2010.jsonl`
Compression will be provided via Apache, as for 1.x.
All of this works with a Play instance running locally (57.8G in about …

Support bulk requests

---

pom.xml

As the "Permanent Generation" was removed in Java 8, on some machines
maven fails with "Unrecognized VM option 'MaxPermSize=256m'".
It's safe to simply remove this option.

Remove obsolete java option

---

src/main/resources/labels/context-labels.json

As we have bibo:Periodical twice, I remove the one with the wrong JSON key "Journal".

Remove redundant and deprecated elements from context

---

src/main/java/de/hbz/lobid/helper/EtikettMaker.java
src/main/resources/labels/context-labels.json
src/main/resources/labels/labels.json
web/conf/context.jsonld

When dealing with owl:class the definitions in the context json-ld
shouldn't use the @type nor the @container infos.
Resolves hbz/lobid-rdf-to-json#59.

Remove superfluous @type & @container from context

---

src/main/resources/morph-hbz01-to-lobid.xml
src/test/resources/hbz01.es.nt
src/test/resources/jsonld/HT010662586
src/test/resources/jsonld/HT010726584
src/test/resources/jsonld/HT016608165
src/test/resources/output/json/01066/HT010662586.json
src/test/resources/output/json/01072/HT010726584.json
src/test/resources/output/json/01660/HT016608165.json
src/test/resources/reverseTest/output/nt/01066/HT010662586.nt
src/test/resources/reverseTest/output/nt/01072/HT010726584.nt
src/test/resources/reverseTest/output/nt/01660/HT016608165.nt

Resolves #363
Removed S.l. (sine locum, without a place). See [example (production)](http://lobid.org/resources/HT016608165) / [example (test)](http://test.lobid.org/resources/HT016608165).

Remove shortcut S.l. for publication place

---

web/app/views/tags/result_doc.scala.html

Will resolve https://github.com/hbz/lobid-resources/issues/339

Fix labelled display of `description` and `tableOfContents`

---

src/main/resources/labels/labels.json

Added language labels if at least 10 resources had that language.
Resolves #439
Assigning it to dr0i for deployment because the scale of the changes isn't visible in the test set. After the deployment I will check if the language label of "http://id.loc.gov/vocabulary/iso639-2/crp" is shown correctly.

Add language labels

---

src/main/resources/labels/context-labels.json
web/conf/context.jsonld

See #187
Removes the leftover `subjectChain` from the context.

Remove subjectChain from context

---

src/main/resources/morph-hbz01-to-lobid.xml
src/test/resources/hbz01.es.nt
src/test/resources/jsonld/HT015090208
src/test/resources/jsonld/HT016382441
src/test/resources/jsonld/HT016556189
src/test/resources/jsonld/HT018939763
src/test/resources/jsonld/TT000075751
src/test/resources/output/json/00007/TT000075751.json
src/test/resources/output/json/01509/HT015090208.json
src/test/resources/output/json/01638/HT016382441.json
src/test/resources/output/json/01655/HT016556189.json
src/test/resources/output/json/01893/HT018939763.json
src/test/resources/reverseTest/output/nt/00007/TT000075751.nt
src/test/resources/reverseTest/output/nt/01509/HT015090208.nt
src/test/resources/reverseTest/output/nt/01638/HT016382441.nt
src/test/resources/reverseTest/output/nt/01655/HT016556189.nt
src/test/resources/reverseTest/output/nt/01893/HT018939763.nt

Here's the next PR for this as we had some problems in the first round (see https://github.com/hbz/lobid-resources/pull/571). This also doesn't have an issue associated with it but I think this is ok for this minor change.
As MAB field 551 holds the "VERLAGS-, PRODUKTIONS- UND BESTELLNUMMER VON MUSIKALIEN UND TONTRAEGERN" (see [MAB documentation](http://www.dnb.de/SharedDocs/Downloads/DE/DNB/standardisierung/mabTitelBibliographischeDaten2001.txt?__blob=publicationFile)) resources with content in this field can be either PublishedScores or AV documents and thus you shouldn't automatically add the publication type "PublishedScore". See also https://jira.hbz-nrw.de/browse/FRL-275. Includes an update of the test data.

Remove mapping of MAB 551 to "PublishedScore"

---

web/app/views/details.scala.html

This adds two tweaks corresponding to the work in progress in https://github.com/hbz/nwbib/issues/163:
- Use `otherTitleInformation` as sub-header: http://stage.lobid.org/resources/HT019478500
- Fix display of superordinate links for articles: http://stage.lobid.org/resources/HT013829089
We have no issue, assigning this pull request for functional review.

Tweaks based on changes for NWBib

---

src/main/resources/index-config.json

Required for scripted aggregation to implement NWBib topic search
See https://github.com/hbz/nwbib/issues/163
@dr0i This pull request is for the ES 5.6 code. It would be great if you could integrate this so that it is available in the ES 5.6 cluster after the Wednesday indexing, independent of our decision about merging the ES 5.6 code into master next week or not.

Add raw keyword sub-field for subject.componentList.label

---

web/app/controllers/resources/Application.java
web/app/controllers/resources/Index.java
web/conf/resources.routes
web/test/tests/InputStringsTest.java
web/test/tests/IntegrationTests.java
web/test/tests/NestedQueryTests.java

Initial use case: restrict NWBib queries to NWBib titles
See:
https://github.com/hbz/nwbib/issues/163
https://github.com/hbz/lobid-gnd/issues/28
Deployed to stage:
http://stage.lobid.org/resources/search?format=json&q=contribution.agent.label:Cornelius+AND+contribution.agent.type:CorporateBody&nested=contribution
http://stage.lobid.org/resources/search?format=json&q=contribution.agent.label:Cornelius+AND+contribution.agent.type:CorporateBody&nested=contribution&filter=inCollection.id:HT014176012

Add `filter` query parameter supporting query string syntax

---

src/main/resources/index-config.json
web/app/controllers/resources/Application.java
web/app/controllers/resources/Index.java
web/app/controllers/resources/LocalIndex.java
web/app/views/api.scala.html
web/conf/resources.conf
web/conf/resources.routes
web/conf/topic.painless
web/test/tests/IndexUnitTest.java
web/test/tests/InputStringsTest.java
web/test/tests/IntegrationTests.java
web/test/tests/NestedQueryTests.java

Interpret `q` param as nested query if `nested` param is not empty, using the value of the `nested` param as the nested field path (see [1]).
Required for https://github.com/hbz/lobid-resources/issues/532 and https://github.com/hbz/nwbib/issues/163
@dr0i:
- This is based on the ES 5.6 code base
- Contains index-config.json changes that should go into the next full staging index
[1]  https://www.elastic.co/guide/en/elasticsearch/reference/5.6/query-dsl-nested-query.html

Set up nested fields and nested queries

---

src/main/resources/labels/context-labels.json
src/test/resources/hbz01.es.nt
src/test/resources/output/json/00306/TT003060418.json
src/test/resources/output/json/01330/HT013304490.json
src/test/resources/reverseTest/output/nt/01305/HT013056453.nt
src/test/resources/reverseTest/output/nt/01330/HT013304490.nt
web/conf/context.jsonld
web/test/tests/RdfConverterTests.java

Will resolve https://github.com/hbz/lobid-resources/issues/652
Data uses uppercase `Location` for `type` of `spatial`, see:
https://lobid.org/resources/HT018472857.json
Context declares a lowercase `location` key, see:
http://lobid.org/resources/context.jsonld
Besides the context change, this pull request expands the RDFConverterTests to test multiple resources.

Fix issue in context, improve RDFConverterTests

---

.gitignore
web/app/views/details_item.scala.html
web/conf/resources.routes

Will resolve https://github.com/hbz/lobid-resources/issues/640
See http://stage.lobid.org/items/HT017412936:DE-361:NA088.88-4442721
The dot in the item ID was interpreted as the dot to specify a format, like:
http://stage.lobid.org/items/HT017412936:DE-361:NA088.88-4442721.json
The routes file now describes the possible formats to support item IDs with dots.
Additionally, this PR tweaks the layout of the item 404 page.

Fix routes for item IDs with dots 

---

src/main/resources/morph-hbz01-to-lobid.xml

Following #675 this avoids MapperParsingExceptions.
Resolves #682.

Enforce literal for dct:bibliographicCitation and callNumber

---

src/main/resources/index-config.json
web/test/tests/IndexIntegrationTest.java

See #763.
Remove the ngram-analyzer because it's not used.
Remnove the german-analyzer because it prevented the number of the notations
to be searchable.
This complements #763.

Make coverage notations searchable

---

web/app/views/tags/items_map.scala.html

Using a lobid proxy anonymizes outgoing traffics of our users.
The wikimedia map server is used via the reverse proxy.
- remove some comments
See hbz/lobid#363.

Use a proxy for tiles

---

web/conf/context.jsonld

The automatically generated context.jsonld of the web-app has also to be updated
when the context jsonld of the ETL is updated.
Complements 3ec2f6f30901247bb7c356eb8edc0fb954673f32.

Complement 3ec2f6f30901247bb7c356eb8edc0fb954673f32

---

pom.xml

The several GB big beacon files were copied to "target" every time maven
was building. This was unneccessary and annoying since copying took some minutes.
See #685.

Exclude the big beacon files from being copied by maven

---

src/main/resources/string2wikidata.tsv

Because NWBib editors want it also matched

Add Dekanate to string2wikidata.tsv

---

src/main/resources/string2wikidata.tsv

Fixes https://github.com/hbz/lobid-resources/issues/962
I did not add "Münster-Mitte" as there is no GSW with this anyway, see http://lobid.org/resources/search?q=coverage:(M%C3%BCnster+AND+Mitte+AND+99)

Update manual wikidata matching

---

src/main/java/org/lobid/resources/ElasticsearchIndexer.java
src/main/java/org/lobid/resources/run/UpdateAliases.java

This adds the alias "resources" to the newest index of "lobid-resources" and
the alias "resources-staging" to the second newest index of "lobid-resources".
The same goes for "geo_nwbib" and "geo_nwbib-staging".
I.e. the aliases found after a fulldump update are switched to go productive.
- improve some logic
- rename some variables to be more pecise in what they stand for
See #968.

Add class for switching index aliases

---

src/main/java/org/lobid/resources/RecordReaderEnhanced.java

The `describedBy.@id` values in the latest EntityFacts dump have 
switched from HTTP to HTTPS URIs, causing the ID creation to break.
This change creates the internal ID from the top-level `@id` field.
See https://github.com/hbz/lobid-gnd/issues/183

Tweak creation of internal Elasticsearch ID

---

src/main/resources/string2wikidata.tsv

Reported by U.P. via email on 2019-04-17:
> in der Raumsystematik bzw. Skos-Datei (?) müsste eine Änderung
> vorgenommen werden. Zur Zeit wird die alte Raumnotation 28 mit GSW
> Monschauer Land zu 28 Monschauer Heckenland umgesetzt. Ich war auch
> irrtümlicherweise der Meinung, dass beides identisch sei. Dem ist aber
> nicht so. Ich habe jetzt in Wikidata den passenden Datensatz zu
> Monschauer Land angelegt. Könnten Sie das noch anpassen?

Adjust mapping for "Monschauer Land"

---

src/main/resources/string2wikidata.tsv

Fixes issue reported via email
(subject "Mismatching  Hamm (Westf)")
by I.M. on 2019-05-22.

Add manual Wikidata mapping for "Hamm"

---

startHbz01ToLobidResources.sh

Date variable was not set.
Improved waiting of rebuilding the geo index, if it failed to be ok:
starting with 15 minutes, then 2h, then 6h45m, 16h16.
See #1032.

Set date variable and improve waiting rebuilding geo index

---

src/main/resources/morph-hbz01-to-lobid.xml
src/test/java/org/lobid/resources/Hbz01MabXml2ElasticsearchLobidTest.java
src/test/resources/hbz01.es.nt
src/test/resources/jsonld/BT000003404
src/test/resources/jsonld/BT000014215
src/test/resources/jsonld/BT000168595
src/test/resources/jsonld/HT004381366
src/test/resources/jsonld/HT008733617
src/test/resources/jsonld/HT009719670
src/test/resources/jsonld/HT013532539
src/test/resources/jsonld/HT013577568
src/test/resources/jsonld/HT014176012
src/test/resources/jsonld/HT014215912
src/test/resources/jsonld/HT015440386
src/test/resources/jsonld/HT016604323
src/test/resources/jsonld/HT016987148
src/test/resources/jsonld/HT017411546
src/test/resources/jsonld/HT017749491
src/test/resources/jsonld/HT018131501
src/test/resources/jsonld/HT018138676
src/test/resources/jsonld/HT018295975
src/test/resources/jsonld/HT018617137
src/test/resources/jsonld/HT018786244
src/test/resources/jsonld/HT019093814
src/test/resources/jsonld/HT019357035

Adds a focus object if the nwbib spatial object resides in nwbib-spatial.tsv.
See #1029.

1029 add focus nwbib spatial

---

src/main/resources/index-config.json
web/test/tests/IndexIntegrationTest.java

Will resolve https://github.com/hbz/nwbib/issues/506
@dr0i: This only affects the index config (except tests). Could you deploy this to (small) test and stage?

Improve tests, remove `stop` filter for default analyzer

---

web/app/views/tags/items_map.scala.html

hbz' tileserver is constrained to zoom level 17.
See https://github.com/hbz/lobid/issues/309.
Test e.g. http://test.lobid.org/resources/TT002009694.

Set maxZoom to 17

---

src/main/resources/alma/common/fields.xml
src/test/resources/alma/(CKB)2560000000104439.json
src/test/resources/alma/(DE-605)HT005207972.json
src/test/resources/alma/(DE-605)HT017398609.json
src/test/resources/alma/(DE-605)HT020202475.json

If an isbn10 exists a corresponding isbn13 is generated.
Also, an isbn is normalized by removing semnatic sugar, so that:
-  "isbn" : [ "3-642-32079-1" ],
+  "isbn" : [ "3642320791", "9783642320798" ],
See #1180.

Enrich isbn

---

web/app/controllers/resources/Webhook.java

Don't create the index name when starting the app but when starting
the ETl of basedump.
See #1159.

Fix create name of index

---

src/main/java/org/lobid/resources/EtikettJson.java
src/main/java/org/lobid/resources/run/AlmaMarcXml2lobidJsonEs.java
src/main/resources/labels/context-labels.json
src/test/java/org/lobid/resources/AlmaMarc21XmlToLobidJsonTest.java
src/test/resources/alma/(DE-605)HT000161712.json
src/test/resources/alma/(DE-605)HT000312236.json
src/test/resources/alma/(DE-605)HT003176544.json
src/test/resources/alma/(DE-605)HT004285445.json
src/test/resources/alma/(DE-605)HT005207972.json
src/test/resources/alma/(DE-605)HT006855611.json
src/test/resources/alma/(DE-605)HT012734833.json
src/test/resources/alma/(DE-605)HT012734884.json
src/test/resources/alma/(DE-605)HT015011399.json
src/test/resources/alma/(DE-605)HT015671602.json
src/test/resources/alma/(DE-605)HT016709661.json
src/test/resources/alma/(DE-605)HT017015300.json
src/test/resources/alma/(DE-605)HT017398609.json
src/test/resources/alma/(DE-605)HT017411546.json
src/test/resources/alma/(DE-605)HT017664407.json
src/test/resources/alma/(DE-605)HT019246898.json
src/test/resources/alma/(DE-605)HT020202475.json
src/test/resources/alma/(DE-605)HT020391499.json
src/test/resources/alma/(DE-605)TT003907920.json
src/test/resources/alma/(DE-605)TT050421649.json
web/conf/context.jsonld

This utilizes the EtikettMaker:
the files in the "labels" directory will be used to ensure all ids of all json objects
have a label. It also creates the context.jsonld residing in
web/conf/context.jsonld.
- add almaIdMMS to labels
- add currentLocation to labels
- add newly created context
See #1257.

Add EtikettJson to the flow

---

src/main/resources/index-config.json

This makes these fields queryable, like:
http://alma.lobid.org/resources/search?q=related.issn:%220955-8810%22&format=json
See #1242.

Index related.[isbn|issn]

---

src/main/resources/labels/context-labels.json
web/conf/context.jsonld

Follows up  #1318.
Removing the "referenceType" in context-labels.json fixes
"jsonld.SyntaxError: Invalid JSON-LD syntax; a term definition must not contain type".
The types of the resources can be lookuped by following the uris of the fields
(aka predicates).

Fix context.json by removing referenceType (#1317)

---

pom.xml
src/main/java/org/lobid/resources/RdfModelFileWriter.java
src/main/resources/schemata/metamorph.xsd

In order to be able to upgrade to metafacture-core 5.3.1:
- use getters/setters in RdfModelFileWriter
- define tabulator in own metamorph.xsd as in metafacture-core's metamorph.xsd

Update metafacture-core dependency to 5.3.1

---

src/main/resources/alma/fix/subjects.fix
src/test/resources/alma-fix/990110509950206441.json
src/test/resources/alma-fix/990110881770206441.json
src/test/resources/alma-fix/990190567380206441.json
src/test/resources/alma-fix/990210312460206441.json

Added the `focus` part of `spatial`.
@dr0i is there still something missing?
@acka47 could you have a look if this is okay like this.
One question I still have there are two `label`s one in `spatial`, one in `focus`. Do they have the same value.
Also can someone explain `coverage` to me? 
Example of the old morph:
https://github.com/hbz/lobid-resources/blob/f290c597648a9c38c0be24b53779c57387856b2d/src/test/resources/jsonld/BT000113394.json#L53
The `label`s and `notation`s of spatial are not the same as the string-value of `coverage`.

Add focus for spatial #1383

---

.gitignore

Added this so that the corresponding ALEPH files are not tracked.

Update gitignore to exclude the alephTest for AlmaFix

---

src/main/resources/log4j2.xml

Also keep logs by append="true".
Atm web/logs/ETL.log is deleted every time a ETL is triggered by webhook.

Roll ETL log

---

src/main/resources/alma/fix/mediumAndType.fix

Resolves #1453
Has no test since this seems to be covered by the other online resource mappings already. But closes a small TODO from #1453

Map Computerdatei(en) im Fernzugriff as online resource #1453

---

src/main/resources/alma/fix/item.fix
src/test/resources/alma-fix/990001412590206441.json
src/test/resources/alma-fix/990050000600206441.json
src/test/resources/alma-fix/990053976760206441.json

#1174 I have set a first try to catch all HOL without ITMs. I saw that 990050000600206441 has also H52 with matching HOL id and it has a duplicate HOL object. Perhaps we could enrich this HOL without ITM with infos from the special H elements?
Also includes the callNumber for entries with H52. See #1188.

Add hasItem Object for HOL without ITM #1174

---

src/main/resources/alma/fix/otherFields.fix
src/test/resources/alma-fix/990110714900206441.json
src/test/resources/alma-fix/990110881770206441.json

Since bibliographicCitation info is not always in 501 but often in 500
I needed to adjust the mapping pattern.
This is different to the mapping here: https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=483000321

Fix bibliographicCitation mapping

---

src/main/java/org/lobid/resources/run/AlmaMarcXmlFix2lobidJsonEs.java
web/app/controllers/resources/WebhookAlmaFix.java

A list of files as input path, separated by ';', will be processed.
- log when file exception appears
- improve log (get stacktrace)

Enable multiple update files (#1619)

---

pom.xml
src/main/java/de/hbz/lobid/helper/CreateWikidataNwbibMaps.java
src/main/java/org/lobid/resources/PipeEncodeTriples.java
src/main/java/org/lobid/resources/RdfModelFileWriter.java
src/main/java/org/lobid/resources/Triples2RdfModel.java
src/test/java/org/lobid/resources/Hbz01MabXmlDeletions2ElasticsearchTest.java
web/app/controllers/resources/RdfConverter.java
web/build.sbt

With https://github.com/metafacture/metafacture-fix/commit/b55bbbf508b2cd484abfa4221649589c06c9db7d#diff-67162ab57d816849d43c537ebdab31a8744ac824f4f512d0462a78d072937a4a a new jena dependency is transitively introduced via metafix.
- update "jena-arq" from "2.10.1" to "3.17.0"
- exclude "commons-codec" from "jsonld-java" dependency
- refactor classes
- remove unnecassary dependencies in buid.sbt (jsonld and jena)
- 
Resolves #1622

Fix jena dependency issue (#1622)

---

src/main/resources/index-config.json

Complements #1640 (as isil was introduced there but the index-config was not configured).
See #1618.

Enable hasItem.heldBy.isil as aggs (#1618)

---

src/main/resources/alma/fix/mediumAndType.fix
src/test/resources/alma-fix/990198383780206441.json
src/test/resources/alma-fix/990198383780206441.xml

Instead of only copying a simple field we need to iterate twice over 300 (r) and $a (r).
Error was reported by the monitoring of ALMA ETL.
The error is the result from the first PR in #1567

EtlError300repeatable

---

web/app/controllers/resources/Accept.java
web/app/controllers/resources/Application.java
web/app/views/details.scala.html
web/conf/resources.conf_template
web/public/stylesheets/resources.css
web/test/tests/AcceptIntegrationTest.java

Add MARC download to API

---

src/main/resources/alma/fix/identifiers.fix
src/main/resources/alma/fix/relatedRessourcesAndLinks.fix
src/test/resources/alma-fix/990108873860206441.json
src/test/resources/alma-fix/990108874370206441.json
src/test/resources/alma-fix/990184127410206441.json
src/test/resources/alma-fix/990193229450206441.json
src/test/resources/alma-fix/990197023370206441.json
src/test/resources/alma-fix/990197067610206441.json
src/test/resources/alma-fix/990197293880206441.json
src/test/resources/alma-fix/990204253490206441.json
src/test/resources/alma-fix/990206060640206441.json
src/test/resources/alma-fix/990210667610206441.json
src/test/resources/alma-fix/990210781980206441.json
src/test/resources/alma-fix/990217495840206441.json
src/test/resources/alma-fix/990226465800206441.json
src/test/resources/alma-fix/990363946050206441.json
src/test/resources/alma-fix/990365842280206441.json
src/test/resources/alma-fix/991002103529706485.json
src/test/resources/alma-fix/99370682219806441.json
src/test/resources/alma-fix/99370694196806441.json
src/test/resources/alma-fix/99371314897806441.json
src/test/resources/alma-fix/99371981001306441.json

Added more related links to fullTextOnline.
Also redid some mapping for urn and doi
Deleted duplicate fullTextOnline-Links.
Urn for edoweb do no resolve.
Compare to old morph: https://github.com/TobiasNx/oldAlephLobid/blob/98bba7f8a93c2ccac7ffd2566149e46dec12a886/morph-hbz01-to-lobid.xml

1757-fullTextOnline

---

src/main/resources/alma/alma.fix
src/main/resources/alma/fix/contribution.fix
src/main/resources/alma/fix/describedBy.fix
src/main/resources/alma/fix/macros.fix
src/main/resources/alma/fix/subjects.fix
src/test/resources/alma-fix/990011470300206441.json
src/test/resources/alma-fix/990065341720206441.json
src/test/resources/alma-fix/990217495840206441.json

Events and meetings have a specific structure for the label. In order to construct them from the Marc Subfields we had to introduce a separate transformation for events.
Also I have put all macros in a separate fix. @blackwinter can you have a look at this. Since I deleted all do once for the single macros but have put it in the maps do once in alma.fix
The macro.fix allows for the usage of the macros in subject.fix and contribution.fix.

1761-gndAndMacro

---

src/main/resources/alma/fix/macros.fix
src/test/resources/alma-fix/990110509950206441.json
src/test/resources/alma-fix/990209817770206441.json

I use the representation as in the GND with brackets, not separated by comma: https://lobid.org/gnd/4115393-5 = > [Niedersachsen (Süd)](https://lobid.org/gnd/4115393-5#)
REsolves #1787

Add subfield $z for other gnd labels and altLabels

---

web/app/controllers/resources/Lobid.java

e.g. for https://lobid.org/resources/990054518830206441
Reported via email by I.N. on 2023-06-27

Parse `long` to avoid NumberFormatException on large numbers

---

web/app/controllers/resources/LocalIndex.java
web/build.sbt
web/test/tests/IndexIntegrationTest.java

Install elasticsearch plugin bundle

---

src/main/resources/alma/alma.fix
src/main/resources/alma/fix/identifiers.fix
src/main/resources/labels/context-labels.json
src/test/resources/alma-fix/990016782920206441.json
src/test/resources/alma-fix/990122511970206441.json
src/test/resources/alma-fix/990123613330206441.json
src/test/resources/alma-fix/990139686910206441.json
src/test/resources/alma-fix/990198383780206441.json
src/test/resources/alma-fix/990209515320206441.json
src/test/resources/alma-fix/990209817770206441.json
src/test/resources/alma-fix/990210237770206441.json
src/test/resources/alma-fix/990210285400206441.json
src/test/resources/alma-fix/990223521400206441.json

Resolves: #1670
Please have a look.
I introduced stockNumber.
I was not sure if I should model this as an array of Objects to state the sources of the stockNumber too. Or just like this.

Add stockNumber #1670

---

src/main/resources/alma/fix/item.fix
src/test/resources/alma-fix/990197293880206441.json
src/test/resources/alma-fix/990199611280206441.json
src/test/resources/alma-fix/99371314897806441.json
src/test/resources/alma-fix/99371791018506441.json

Before item.fix checked every ITM Field before creating a HOL-Holding ("PhysikalischerTitel") and checked every POR and HOL before creating a MBD-Holding ("NurTitel").
Now it is using helper elements `"@ITM-H"` and `"@HOL-M_POR-M"`. It makes the transformation ~~a lot~~ faster by reducing the in-conditionals with wildcards.

Use helper elements when creating HOL and MBD holdings

---

src/main/resources/alma/fix/identifiers.fix
src/test/resources/alma-fix/991002103529706485.json

Resolves #1925
Creating links that contain DOIs but are not DOI resolver links are  not reliable to identify DOIs.

Create DOIs only from true DOI resolver links #1925

---

web/scripts/getLogsErrorsETL.sh
web/scripts/getLogsEtlFixErrors.sh
web/scripts/getMultipleHbzid.sh
web/scripts/getWebhookCallerLogs.sh

Completes  #1930.
See  #1847.
Crontab is adjusted.

Adjust paths to log files in log checking scripts

---

src/main/resources/alma/maps/institutions.tsv
src/test/resources/alma-fix/990197293880206441.json
src/test/resources/alma-fix/99370678063606441.json
src/test/resources/alma-fix/99371791018506441.json

Source: https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=813989955
Related to: DigiBib-Ticket#2023111050346536
See also: hbz/lookup-tables#23
Example: [99373068397506441](https://lobid.org/resources/99373068397506441)

Use correct ISIL for Hochschule Hamm-Lippstadt.

---

src/main/resources/alma/index-config.json
web/app/controllers/resources/Queries.java

See https://jira.hbz-nrw.de/browse/RPB-37

Rename biblioVinoId to schoeneNummer (RPB-37)

---

src/main/resources/alma/fix/otherFields.fix
src/main/resources/alma/fix/relatedRessourcesAndLinks.fix
src/test/resources/alma-fix/99371530278506441.json
src/test/resources/alma-fix/99372423490706441.json

Add language to ExampleOfWork (#1823)

---

src/main/resources/alma/fix/mediumAndType.fix
src/test/resources/alma-fix/990193806600206441.json

Resolves #1970 
Maps have not yet been included in the "print" medium, so the "Miscellaneous" label was set by default.

Add non-electronics maps to the medium "print"

---

src/main/resources/alma/fix/otherFields.fix
src/test/resources/alma-fix/990198383780206441.json
src/test/resources/alma-fix/99371426239306441.json
src/test/resources/alma-fix/99371426239306441.xml

Adjust replacement of brackets

Fix extent for repeated 300 with multiple Subfields

---

src/main/resources/alma/fix/contribution.fix
src/test/resources/alma-fix/99371463467006441.json
src/test/resources/alma-fix/99371463467006441.xml

Fix contribution transformation

---

src/main/resources/alma/fix/macros.fix
src/main/resources/alma/fix/otherFields.fix
src/main/resources/alma/fix/titleRelatedFields.fix
src/test/resources/alma-fix/990141342350206441.json
src/test/resources/alma-fix/990202474680206441.json

See #1836 and also https://github.com/hbz/nwbib/issues/589
Was decided in https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=19136520 but was never implemented.

1836-beigefügtesWerk

---

src/test/resources/schemas/hasItem.json

Schema only accepted `Item` as `type` in `hasItem` but we also have additional type classes:
`PhysicalObject`, `DigitalDocument`, `NurTitel`, `PhysikalischerTitel`
Since #1699 is not solved yet @maipet suggested to loosen up the type specification. (Written by @TobiasNx )

Schema: Adjust hasItem: loose constant value for type property #1340

---

src/main/resources/alma/fix/subjects.fix
src/main/resources/alma/maps/classification.tsv
src/test/resources/alma-fix/990053976760206441.json
src/test/resources/alma-fix/990054345550206441.json
src/test/resources/alma-fix/990104908070206441.json
src/test/resources/alma-fix/990108873860206441.json
src/test/resources/alma-fix/990109712970206441.json
src/test/resources/alma-fix/990156060190206441.json
src/test/resources/alma-fix/990166236770206441.json
src/test/resources/alma-fix/990170546170206441.json
src/test/resources/alma-fix/990196925330206441.json
src/test/resources/alma-fix/990197023370206441.json
src/test/resources/alma-fix/991005935279706485.json

See #2045 and #2047
We have some notation/concept systems that were not mapped properly.
If they are `z` they are not defined but sorted under "Other",
`sswd`  on the other hand is the GND Systematik as SKOS System.
Not sure if we should also use the Labels for the GND Systematik.
This will also fix some validation errors from #1340

Improve some subject mappings

---

src/main/resources/alma/fix/mediumAndType.fix
src/main/resources/labels/context-labels.json
src/test/resources/alma-fix/990133067580206441.json
src/test/resources/schemas/type.json

Add mapping for type vivo:Database See #1864

1864-database

---

src/main/resources/alma/fix/mediumAndType.fix
src/main/resources/alma/fix/relatedRessourcesAndLinks.fix
src/test/resources/alma-fix/990133067580206441.json

Add DBIS refrence #1864

---

web/app/views/tags/result_doc.scala.html
web/app/views/tags/result_field.scala.html

Resolves #1951 and  #1829 Wrong ISBN and ISSN
and also fixes #1992 missing linking to Bände and Enthält
https://github.com/hbz/nwbib/issues/636

Reuse nwbib fix for #1992, #1951 and  #1829

---

src/main/resources/alma/fix/identifiers.fix
src/main/resources/alma/fix/relatedRessourcesAndLinks.fix
src/test/resources/alma-fix/990177418660206441.json
src/test/resources/alma-fix/990177418660206441.xml
src/test/resources/alma-fix/990184766040206441.json
src/test/resources/alma-fix/990184766040206441.xml
web/test/tests/IndexIntegrationTest.java

This PR resolves #2070
It makes all the mappings for 856 less strict concerning the indices it enables the transformation to get more fullTextOnline info aswell as other relevant information as DOI.

Make mapping for 856 less strict #2070

---

web/app/controllers/resources/Application.java
web/app/views/api.scala.html
web/test/tests/SuggestionsTest.java

Like in lobid-gnd: configure fields to use in the `format` param (e.g. `json:title,contribution`), or use `format=json:suggest` for default fields.
See https://jira.hbz-nrw.de/browse/RPB-141
Deployed to test: https://test.lobid.org/resources/api#auto-complete

Support auto-complete suggestions created from multiple fields

---

src/main/resources/alma/fix/otherFields.fix
src/test/resources/alma-fix/990126426530206441.json
src/test/resources/alma-fix/990126426530206441.xml
src/test/resources/alma-fix/990173607780206441.json
src/test/resources/alma-fix/990173607780206441.xml
web/test/tests/IndexIntegrationTest.java

See #2062
@maipet could you have a look. 
You also had a list of more not matching values. Could you check if you can add any additional mapping?

Skip not language info that are not three letters long

---

src/main/resources/alma/fix/titleRelatedFields.fix
src/test/resources/alma-fix/99374153235806441.json

Related to #2089
Deletes the not needed brackets that lead to overwriting the publication dates from `"264` by `008`

Fix fallback for publication dates #2089

---

src/main/resources/alma/fix/identifiers.fix
src/test/resources/alma-fix/99370673692206441.json
src/test/resources/alma-fix/99370673692206441.xml
web/test/tests/IndexIntegrationTest.java

Fix broken zdbId #2093

---

src/main/resources/alma/fix/otherFields.fix
src/test/resources/alma-fix/99371123630706441.json

Improved the mapping. To fetch 540 and not only 542 for licensing info.
We could discuss, if we also intend to catch licensing info from 856 but I am not sure yet. And I have no example.

Adjust license mapping to map 540 Open Access infos  #2103

---

src/main/resources/alma/fix/identifiers.fix
src/test/resources/alma-fix/991000128689108979.json
src/test/resources/alma-fix/991000128689108979.xml

Talked to Verbundgruppe N.D. she said conceptually no local records should have hbzIds but local libraries often do not delete them. Therefore I suggest deleting them in lobid.

2108-noLocalHbzIds

---

src/main/resources/alma/fix/identifiers.fix
src/test/resources/alma-fix/990217879290206441.json

See #2112.
zdbId links should not be added if DE-599 states zdbInfo. following the info of Verbundgruppe. See #2112

Do not add zdbId if only DE-599 has ZDB info #2112

---

web/app/views/tags/result_doc.scala.html

Resolves #2133
@fsteeg could you code review this and deploy this to test for @acka47 to review? Thanks

Move all identifier into on separate section #2133

---

src/main/resources/alma/fix/describedBy.fix
src/main/resources/alma/fix/macros.fix
src/main/resources/alma/fix/titleRelatedFields.fix
src/test/resources/alma-fix/990129250080206441.json
src/test/resources/alma-fix/990129250080206441.xml
web/test/tests/IndexIntegrationTest.java

See #2141
ElasticSearch throws `MapperParsingException` if leap year date 02-29 is not correct. I introduced a simple regex to test this part of this answer:
https://stackoverflow.com/a/8648129
Tests for range 1800-2099 and changes to date to 02-28 if leap year date is incorrect.

Validate leapYear #2141

---

src/main/resources/alma/fix/otherFields.fix
src/test/resources/alma-fix/990110714900206441.json
src/test/resources/alma-fix/990110881770206441.json
src/test/resources/alma-fix/990112067120206441.json
src/test/resources/alma-fix/990126426530206441.json

If the field contains a citation ("In:"), the content gets added to both `note` and `bibliographicCitation`.
Ex.: 990110402310206441

Avoid duplicating MARC 500 (General Note).
